namespace Navigator.Data.Enums.Metric;

public enum MetricSeriesType
{
    DatabaseSize,

    RisIdsActive,
    RisIdsInactive,

    JourneyTotal,

    TransportTypesTotal,

    HourlyGlobalArrivals,
    HourlyGlobalArrivalCancellations,
    HourlyGlobalArrivalDelaySum,
    HourlyGlobalArrivalDelaySampleCount,
    HourlyGlobalArrivalPunctualCount,
    HourlyGlobalArrivalDelayMinorCount,
    HourlyGlobalArrivalDelayMajorCount,
    HourlyGlobalArrivalDelaySevereCount,
    HourlyGlobalArrivalPlatformChanges,
    HourlyGlobalDepartures,
    HourlyGlobalDepartureCancellations,
    HourlyGlobalDepartureDelaySum,
    HourlyGlobalDepartureDelaySampleCount,
    HourlyGlobalDeparturePunctualCount,
    HourlyGlobalDepartureDelayMinorCount,
    HourlyGlobalDepartureDelayMajorCount,
    HourlyGlobalDepartureDelaySevereCount,
    HourlyGlobalDeparturePlatformChanges,

    StationArrivals,
    StationArrivalCancellations,
    StationArrivalDelayAvg,
    StationArrivalPunctualityRate,
    StationArrivalDelayMinor,
    StationArrivalDelayMajor,
    StationArrivalDelaySevere,
    StationArrivalPlatformChanges,
    StationDepartures,
    StationDepartureCancellations,
    StationDepartureDelayAvg,
    StationDeparturePunctualityRate,
    StationDepartureDelayMinor,
    StationDepartureDelayMajor,
    StationDepartureDelaySevere,
    StationDeparturePlatformChanges,

    StationTimelineArrivals,
    StationTimelineArrivalCancellations,
    StationTimelineArrivalDelayAvg,
    StationTimelineArrivalPunctualityRate,
    StationTimelineArrivalPlatformChanges,
    StationTimelineDepartures,
    StationTimelineDepartureCancellations,
    StationTimelineDepartureDelayAvg,
    StationTimelineDeparturePunctualityRate,
    StationTimelineDeparturePlatformChanges,

    JourneyServiceOperatorJourneys,
    JourneyServiceOperatorCancellations,
    JourneyServiceDailyOperatorJourneys,
    JourneyServiceDailyOperatorCancellations,
    JourneyServiceJourneyTypeJourneys,
    JourneyServiceReplacementTransports,

    MessageDisruptionCauses,
    MessageDailyTypes,
    StationMessageDisruptions,
    StationMessageAffectedStops,
}
