services:
  navigator-frontend:
    container_name: navigator-frontend
    image: ghcr.io/schmolldechse/navigator-frontend:latest
    restart: always
    ports: [ "3000:3000" ]
    networks: [ "navigator-network" ]
    environment:
      PUBLIC_BACKEND_BASE_URL: ${PUBLIC_BACKEND_BASE_URL}
      BACKEND_DOCKER_BASE_URL: ${BACKEND_DOCKER_BASE_URL}

  navigator-backend:
    container_name: navigator-backend
    image: ghcr.io/schmolldechse/navigator-backend:latest
    restart: always
    ports: [ "8000:8000" ]
    networks: [ "navigator-network" ]
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_DATABASE_URL: ${AUTH_DATABASE_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

  navigator-redis:
    container_name: navigator-redis
    image: redis:latest
    restart: always
    ports: [ "6379:6379" ]
    networks: [ "navigator-network" ]
    volumes:
      - ./redis:/usr/local/etc/redis
      - navigator-stations:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  navigator-postgres:
    container_name: navigator-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: [ "5432:5432" ]
    networks: [ "navigator-network" ]
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

networks:
  navigator-network:
    driver: bridge

volumes:
  navigator-stations:
  postgres_data:
