services:
  navigator-frontend:
    container_name: navigator-frontend
    image: schmolldechsee/navigator-frontend:latest
    restart: always
    ports: [ "3000:3000" ]
    networks: [ "navigator-network" ]
    environment:
      PUBLIC_BACKEND_BASE_URL: ${PUBLIC_BACKEND_BASE_URL}
      BACKEND_DOCKER_BASE_URL: ${BACKEND_DOCKER_BASE_URL}

  navigator-backend:
    container_name: navigator-backend
    image: schmolldechsee/navigator-backend:latest
    restart: always
    ports: [ "8000:8000" ]
    networks: [ "navigator-network" ]
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  navigator-redis:
    container_name: navigator-redis
    image: redis:latest
    restart: always
    ports: [ "6379:6379" ]
    networks: [ "navigator-network" ]
    volumes:
      - ./redis:/usr/local/etc/redis
      - navigator-stations:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

networks:
  navigator-network:
    driver: bridge

volumes:
  navigator-stations:
