services:
  navigator-frontend:
    container_name: navigator-frontend
    image: ghcr.io/schmolldechse/navigator-frontend:latest
    restart: always
    ports: [ "3000:3000" ]
    networks: [ "navigator-network" ]
    environment:
      PUBLIC_BACKEND_BASE_URL: ${PUBLIC_BACKEND_BASE_URL}
      BACKEND_DOCKER_BASE_URL: ${BACKEND_DOCKER_BASE_URL}

  navigator-backend:
    container_name: navigator-backend
    image: ghcr.io/schmolldechse/navigator-backend:latest
    restart: always
    ports: [ "8000:8000" ]
    networks: [ "navigator-network" ]
    depends_on:
      - navigator-mongodb
      - navigator-postgres
    environment:
      MONGO_URL: ${MONGO_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_POSTGRES_URL: ${AUTH_POSTGRES_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

  navigator-daemon:
    container_name: navigator-daemon
    image: ghcr.io/schmolldechse/navigator-daemon:latest
    restart: on-failure
    networks: [ "navigator-network" ]
    depends_on:
      - navigator-mongodb
    environment:
      MONGO_URL: ${MONGO_URL}

  navigator-mongodb:
    container_name: navigator-mongodb
    image: bitnami/mongodb:latest
    restart: always
    ports: [ "27017:27017" ]
    networks: [ "navigator-network" ]
    environment:
      MONGODB_ROOT_PASSWORD: strong-password-here
      MONGODB_EXTRA_DATABASES: ${MONGODB_EXTRA_DATABASES}
      MONGODB_EXTRA_USERNAMES: ${MONGODB_EXTRA_USERNAMES}
      MONGODB_EXTRA_PASSWORDS: ${MONGODB_EXTRA_PASSWORDS}
    volumes:
      - mongodb_data:/bitnami/mongodb

  navigator-postgres:
    container_name: navigator-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: [ "5432:5432" ]
    networks: [ "navigator-network" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  navigator-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
