services:
  navigator-frontend:
    container_name: navigator-frontend
    image: schmolldechsee/navigator-frontend:latest
    restart: always
    ports: [ "3000:3000" ]
    networks: [ "navigator-network" ]

  navigator-backend:
    container_name: navigator-backend
    image: schmolldechsee/navigator-backend:latest
    restart: always
    ports: [ "8000:8000" ]
    networks: [ "navigator-network" ]
    environment:
      REDIS_HOST: navigator-redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_USER: navigator-stations
      REDIS_PASSWORD: pass-your-pw-here

  navigator-redis:
    container_name: navigator-redis
    image: redis:latest
    restart: always
    ports: [ "6379:6379" ]
    networks: [ "navigator-network" ]
    volumes:
      - ./redis:/usr/local/etc/redis
      - navigator-stations:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

networks:
  navigator-network:
    driver: bridge

volumes:
  navigator-stations: