services:
  navigator-frontend:
    container_name: navigator-frontend
    image: ghcr.io/schmolldechse/navigator-frontend:latest
    restart: always
    ports: [ "3000:3000" ]
    networks: [ "navigator-network" ]
    depends_on:
      - navigator-backend
    environment:
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL}
      PRIVATE_BACKEND_URL: ${PRIVATE_BACKEND_URL}

  navigator-backend:
    container_name: navigator-backend
    image: ghcr.io/schmolldechse/navigator-backend:latest
    restart: always
    ports: [ "8000:8000" ]
    networks: [ "navigator-network" ]
    depends_on:
      - navigator-postgres
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}

  navigator-daemon:
    container_name: navigator-daemon
    image: ghcr.io/schmolldechse/navigator-daemon:latest
    restart: on-failure
    networks: [ "navigator-network" ]
    depends_on:
      - navigator-postgres
    environment:
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}

  navigator-postgres:
    container_name: navigator-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: [ "5432:5432" ]
    networks: [ "navigator-network" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  navigator-network:
    driver: bridge

volumes:
  postgres_data: