// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: "https://navigator.voldechse.wtf/" | (string & {});
};

export type BaseStation = {
	evaNumber: number | string;
	name: string;
	position: StationPosition;
};

export enum InformationType {
	JOURNEY_ATTRIBUTE = "JOURNEY_ATTRIBUTE",
	DISRUPTION = "DISRUPTION",
	MESSAGE = "MESSAGE",
	RIS_QUALITY_DEVIATION = "RIS_QUALITY_DEVIATION",
	RIS_CAUSE_REASON = "RIS_CAUSE_REASON"
}

export type Journey = {
	journeyId: string;
	administration: JourneyAdministration;
	type: JourneyType;
	transport: JourneyTransport;
	continuationBy?: Array<string>;
	continuationFor?: Array<string>;
	cancelled: boolean;
	destination: JourneyRichStopPlace;
	differingDestination?: null | JourneyStopPlace;
	origin: JourneyRichStopPlace;
	differingOrigin?: null | JourneyStopPlace;
	scheduledEvents: Array<JourneyScheduledEvent>;
	messages: Array<JourneyMessage>;
};

export type JourneyAdministration = {
	administrationId: string;
	operatorCode: string;
	operatorName: string;
};

export type JourneyMessage =
	| ({
			type?: "ATTRIBUTE";
	  } & JourneyMessageAttributeMessage)
	| ({
			type?: "DISRUPTION";
	  } & JourneyMessageDisruptionMessage)
	| ({
			type?: "NOTE";
	  } & JourneyMessageNoteMessage)
	| ({
			type?: "RIS_CAUSE";
	  } & JourneyMessageRisCauseMessage)
	| ({
			type?: "RIS_QUALITY_DEVIATION";
	  } & JourneyMessageRisQualityDeviationMessage);

export type JourneyMessageAttributeMessage = {
	type?: "ATTRIBUTE";
	messageId: number | string;
	key: MessageKey;
	text: string;
};

export type JourneyMessageDisruptionMessage = {
	type?: "DISRUPTION";
	cause?: null | string;
	effect?: null | string;
	disruptionId?: null | string;
	textShort?: null | string;
	references?: null | Array<JourneyMessageReference>;
	messageId: number | string;
	key: MessageKey;
	text: string;
};

export type JourneyMessageNoteMessage = {
	type?: "NOTE";
	category?: null | string;
	textShort?: null | string;
	references?: null | Array<JourneyMessageReference>;
	messageId: number | string;
	key: MessageKey;
	text: string;
};

export type JourneyMessageReference = {
	referenceType: MessageReferenceType;
	url?: null | string;
	label?: null | string;
};

export type JourneyMessageRisCauseMessage = {
	type?: "RIS_CAUSE";
	messageId: number | string;
	key: MessageKey;
	text: string;
};

export type JourneyMessageRisQualityDeviationMessage = {
	type?: "RIS_QUALITY_DEVIATION";
	messageId: number | string;
	key: MessageKey;
	text: string;
};

export type JourneyRichStopPlace = {
	cancelled: boolean;
	name: string;
	evaNumber: number | string;
};

export type JourneyScheduledEvent = {
	stopPlace: JourneyStopPlace;
	differingStopPlace: JourneyStopPlace;
	cancelled: boolean;
	additional: boolean;
	noPassengerChange: boolean;
	demand: boolean;
	scheduleType: ScheduleType;
	plannedTime: string;
	actualTime: string;
	delay: number | string;
	plannedPlatform?: null | string;
	actualPlatform?: null | string;
	timeType: TimeType;
	travelsWith?: null | Array<string>;
	messageIds?: null | Array<number | string>;
};

export type JourneyStopPlace = {
	name: string;
	evaNumber: number | string;
};

export type JourneyTransport = {
	type: TransportType;
	replacementType?: null | TransportType;
	category?: null | string;
	categoryInternal?: null | string;
	journeyDescription: string;
	number: number | string;
	line?: null | string;
};

export enum JourneyType {
	REGULAR = "REGULAR",
	REPLACEMENT = "REPLACEMENT",
	RELIEF = "RELIEF",
	EXTRA = "EXTRA"
}

export enum MessageKey {
	UNPLANNED_INFO = "UNPLANNED_INFO",
	GENERAL_WARNING = "GENERAL_WARNING",
	ADDITIONAL_COACHES = "ADDITIONAL_COACHES",
	MISSING_COACHES = "MISSING_COACHES",
	CHANGED_COACH_SEQUENCE = "CHANGED_COACH_SEQUENCE",
	REPLACEMENT_SERVICE = "REPLACEMENT_SERVICE",
	ADDITIONAL_STOP = "ADDITIONAL_STOP",
	WIFI_DISTRIBUTION = "WIFI_DISTRIBUTION",
	NO_FIRST_CLASS = "NO_FIRST_CLASS",
	ACCESSIBILITY_WARNING = "ACCESSIBILITY_WARNING",
	RESERVATIONS_MISSING = "RESERVATIONS_MISSING",
	RESERVATIONS_REQUIRED = "RESERVATIONS_REQUIRED",
	NO_FOOD = "NO_FOOD",
	BICYCLE_WARNING = "BICYCLE_WARNING",
	BICYCLE_TRANSPORT = "BICYCLE_TRANSPORT",
	BICYCLE_TRANSPORT_NOT_POSSIBLE = "BICYCLE_TRANSPORT_NOT_POSSIBLE",
	BICYCLE_RESERVATION_REQUIRED = "BICYCLE_RESERVATION_REQUIRED",
	TICKET_INFORMATION = "TICKET_INFORMATION"
}

export enum MessageReferenceType {
	LINK = "LINK",
	IMAGE = "IMAGE",
	ATTACHMENT = "ATTACHMENT"
}

export type MetricDataPoint = {
	timestamp: string;
	value: number | string;
};

/**
 * Represents a request to query specific metrics within a time range.
 */
export type MetricQueryRequest = {
	/**
	 * The start time of the range for which to retrieve metrics.
	 */
	start: string;
	/**
	 * The start time of the range for which to retrieve metrics.
	 */
	end: string;
	/**
	 * The specific type of metric to retrieve.
	 */
	queryType: MetricQueryType;
	cumulativeValues: boolean;
};

export enum MetricQueryType {
	DATABASE_SIZE = "DATABASE_SIZE",
	RIS_IDS = "RIS_IDS",
	JOURNEYS = "JOURNEYS"
}

/**
 * Represents a series of measured data points for a specific metric over a time range.
 */
export type MetricSeries = {
	seriesType: MetricSeriesType;
	unit: MetricUnit;
	timerange: Timerange;
	isCumulative?: boolean;
	/**
	 * Aggregated statistics about this series (e.g. totals, deltas).
	 */
	summary: MetricSummary;
	dataPoints: Array<MetricDataPoint>;
};

export enum MetricSeriesType {
	DATABASE_SIZE = "DATABASE_SIZE",
	RIS_IDS_ACTIVE = "RIS_IDS_ACTIVE",
	RIS_IDS_INACTIVE = "RIS_IDS_INACTIVE",
	JOURNEY_TOTAL = "JOURNEY_TOTAL",
	JOURNEY_DAILY = "JOURNEY_DAILY"
}

export type MetricSummary = {
	startValue: number | string;
	endValue: number | string;
	absoluteChange: number | string;
	minValue: number | string;
	maxValue: number | string;
};

export enum MetricUnit {
	BYTES = "BYTES",
	COUNT = "COUNT"
}

export type ProblemDetails = {
	type?: null | string;
	title?: null | string;
	status?: null | number | string;
	detail?: null | string;
	instance?: null | string;
};

export enum ScheduleType {
	ARRIVAL = "ARRIVAL",
	DEPARTURE = "DEPARTURE"
}

export type Station = {
	transports: Array<TransportType>;
	ril100?: null | Array<string>;
	evaNumber: number | string;
	name: string;
	position: StationPosition;
};

/**
 * Represents a request to find stations near specific geographic coordinates.
 */
export type StationByGeographicCoordinatesRequest = {
	/**
	 * The latitude of the location.
	 */
	latitude: number | string;
	/**
	 * The longitude of the location.
	 */
	longitude: number | string;
	/**
	 * The maximum number of stations to return. Defaults to 100.
	 */
	limit?: null | number | string;
	/**
	 * The maximum distance in meters to search for stations. Defaults to 1000.
	 */
	maxDistance?: null | number | string;
};

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location
 * types.
 */
export type StationBySerchtermRequest = {
	/**
	 * The term to search for in station names or codes.
	 */
	searchTerm: string;
	/**
	 * The maximum number of results to return. Defaults to 10 if not specified.
	 */
	maxResults?: null | number | string;
	/**
	 * An array of location types to filter the search results. Defaults to ['ALL'] if not specified.
	 */
	locationTypes?: null | Array<string>;
};

export type StationGatheringInfo = {
	queryingEnabled: boolean;
	lastQueried?: null | string;
	active: Array<TransportType>;
	disabled: Array<TransportType>;
};

export type StationPosition = {
	latitude: number | string;
	longitude: number | string;
};

export type Timerange = {
	start: string;
	end: string;
};

export type TimetableArrival = {
	journeyId: string;
	administration: TimetableEntryAdministration;
	transport: TimetableEntryTransport;
	origin: TimetableEntryRichStopPlace;
	differingOrigin?: null | TimetableEntryRichStopPlace;
	direction: Array<TimetableEntryStopPlace>;
	viaStops: Array<TimetableEntryRichStopPlace>;
	schedule: TimetableEntrySchedule;
	informations: Array<TimetableEntryInformation>;
	cancelled: boolean;
	additional?: null | boolean;
	demand?: null | boolean;
	travelsWith?: null | Array<string>;
};

export type TimetableDeparture = {
	journeyId: string;
	administration: TimetableEntryAdministration;
	transport: TimetableEntryTransport;
	destination: TimetableEntryRichStopPlace;
	differingDestination?: null | TimetableEntryRichStopPlace;
	direction: Array<TimetableEntryStopPlace>;
	viaStops: Array<TimetableEntryRichStopPlace>;
	schedule: TimetableEntrySchedule;
	informations: Array<TimetableEntryInformation>;
	cancelled: boolean;
	additional?: null | boolean;
	demand?: null | boolean;
	travelsWith?: null | Array<TimetableEntryCoupledTransport>;
};

export type TimetableEntryAdministration = {
	administrationId: string;
	operatorCode: string;
	operatorName: string;
};

export type TimetableEntryCoupledTransport = {
	journeyId: string;
	separationAt: TimetableEntryStopPlace;
};

export type TimetableEntryInformation = {
	type: InformationType;
	key: MessageKey;
	text: string;
	textShort?: null | string;
};

export type TimetableEntryRichStopPlace = {
	cancelled: boolean;
	additional?: null | boolean;
	name: string;
	evaNumber: number | string;
};

export type TimetableEntrySchedule = {
	plannedTime: string;
	actualTime: string;
	delay?: number | string;
	plannedPlatform?: null | string;
	actualPlatform?: null | string;
	timeType: TimeType;
};

export type TimetableEntryStopPlace = {
	name: string;
	evaNumber: number | string;
};

export type TimetableEntryTransport = {
	type: TransportType;
	replacementType?: null | TransportType;
	category?: null | string;
	categoryInternal?: null | string;
	journeyType: JourneyType;
	journeyDescription: string;
	number: number | string;
	line?: null | string;
};

/**
 * Represents a request to retrieve a timetable for a specific station, including the station's EVA number, the desired
 * date and time, and the duration for which to retrieve timetable data.
 */
export type TimetableRequest = {
	/**
	 * The evaNumber to lookup a timetable for
	 */
	evaNumber: number | string;
	/**
	 * The date and time for which to retrieve the timetable. Defaults to the current date and time if not specified.
	 */
	when?: null | string;
	/**
	 * The duration in minutes for which to retrieve the timetable. Defaults to 60 minutes if not specified.
	 */
	duration?: null | number | string;
};

export enum TimeType {
	SCHEDULE = "SCHEDULE",
	PREVIEW = "PREVIEW",
	REAL = "REAL"
}

export enum TransportType {
	UNKNOWN = "UNKNOWN",
	HIGH_SPEED_TRAIN = "HIGH_SPEED_TRAIN",
	INTERCITY_TRAIN = "INTERCITY_TRAIN",
	INTER_REGIONAL_TRAIN = "INTER_REGIONAL_TRAIN",
	REGIONAL_TRAIN = "REGIONAL_TRAIN",
	CITY_TRAIN = "CITY_TRAIN",
	SUBWAY = "SUBWAY",
	TRAM = "TRAM",
	BUS = "BUS",
	FERRY = "FERRY",
	FLIGHT = "FLIGHT",
	CAR = "CAR",
	TAXI = "TAXI",
	SHUTTLE = "SHUTTLE",
	BIKE = "BIKE",
	SCOOTER = "SCOOTER",
	WALK = "WALK"
}

export type GetApiV1JourneyData = {
	body?: never;
	path?: never;
	query?: {
		journeyId?: string;
	};
	url: "/api/v1/journey";
};

export type GetApiV1JourneyErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type GetApiV1JourneyError = GetApiV1JourneyErrors[keyof GetApiV1JourneyErrors];

export type GetApiV1JourneyResponses = {
	/**
	 * OK
	 */
	200: Journey;
};

export type GetApiV1JourneyResponse = GetApiV1JourneyResponses[keyof GetApiV1JourneyResponses];

export type PostApiV1JourneyBatchData = {
	body: Array<string>;
	path?: never;
	query?: never;
	url: "/api/v1/journey/batch";
};

export type PostApiV1JourneyBatchErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1JourneyBatchError = PostApiV1JourneyBatchErrors[keyof PostApiV1JourneyBatchErrors];

export type PostApiV1JourneyBatchResponses = {
	/**
	 * OK
	 */
	200: Array<Journey>;
};

export type PostApiV1JourneyBatchResponse = PostApiV1JourneyBatchResponses[keyof PostApiV1JourneyBatchResponses];

export type GetApiV1StationsData = {
	body?: never;
	path?: never;
	query?: {
		evaNumber?: number | string;
	};
	url: "/api/v1/stations";
};

export type GetApiV1StationsErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * Not Found
	 */
	404: ProblemDetails;
};

export type GetApiV1StationsError = GetApiV1StationsErrors[keyof GetApiV1StationsErrors];

export type GetApiV1StationsResponses = {
	/**
	 * OK
	 */
	200: Station;
};

export type GetApiV1StationsResponse = GetApiV1StationsResponses[keyof GetApiV1StationsResponses];

export type PostApiV1StationsData = {
	body: StationBySerchtermRequest;
	path?: never;
	query?: never;
	url: "/api/v1/stations";
};

export type PostApiV1StationsErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1StationsError = PostApiV1StationsErrors[keyof PostApiV1StationsErrors];

export type PostApiV1StationsResponses = {
	/**
	 * OK
	 */
	200: Array<Station>;
};

export type PostApiV1StationsResponse = PostApiV1StationsResponses[keyof PostApiV1StationsResponses];

export type PostApiV1StationsNearbyData = {
	body: StationByGeographicCoordinatesRequest;
	path?: never;
	query?: never;
	url: "/api/v1/stations/nearby";
};

export type PostApiV1StationsNearbyErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1StationsNearbyError = PostApiV1StationsNearbyErrors[keyof PostApiV1StationsNearbyErrors];

export type PostApiV1StationsNearbyResponses = {
	/**
	 * OK
	 */
	200: Array<BaseStation>;
	/**
	 * No Content
	 */
	204: void;
};

export type PostApiV1StationsNearbyResponse = PostApiV1StationsNearbyResponses[keyof PostApiV1StationsNearbyResponses];

export type GetApiV1StationsGatheringData = {
	body?: never;
	path?: never;
	query?: {
		evaNumber?: number | string;
	};
	url: "/api/v1/stations/gathering";
};

export type GetApiV1StationsGatheringErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * Not Found
	 */
	404: ProblemDetails;
};

export type GetApiV1StationsGatheringError = GetApiV1StationsGatheringErrors[keyof GetApiV1StationsGatheringErrors];

export type GetApiV1StationsGatheringResponses = {
	/**
	 * OK
	 */
	200: StationGatheringInfo;
};

export type GetApiV1StationsGatheringResponse = GetApiV1StationsGatheringResponses[keyof GetApiV1StationsGatheringResponses];

export type PostApiV1StatisticsMetricsData = {
	body: MetricQueryRequest;
	path?: never;
	query?: never;
	url: "/api/v1/statistics/metrics";
};

export type PostApiV1StatisticsMetricsErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1StatisticsMetricsError = PostApiV1StatisticsMetricsErrors[keyof PostApiV1StatisticsMetricsErrors];

export type PostApiV1StatisticsMetricsResponses = {
	/**
	 * OK
	 */
	200: Array<MetricSeries>;
};

export type PostApiV1StatisticsMetricsResponse = PostApiV1StatisticsMetricsResponses[keyof PostApiV1StatisticsMetricsResponses];

export type PostApiV1TimetableDeparturesData = {
	body: TimetableRequest;
	path?: never;
	query?: never;
	url: "/api/v1/timetable/departures";
};

export type PostApiV1TimetableDeparturesErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1TimetableDeparturesError = PostApiV1TimetableDeparturesErrors[keyof PostApiV1TimetableDeparturesErrors];

export type PostApiV1TimetableDeparturesResponses = {
	/**
	 * OK
	 */
	200: Array<TimetableDeparture>;
};

export type PostApiV1TimetableDeparturesResponse =
	PostApiV1TimetableDeparturesResponses[keyof PostApiV1TimetableDeparturesResponses];

export type PostApiV1TimetableArrivalsData = {
	body: TimetableRequest;
	path?: never;
	query?: never;
	url: "/api/v1/timetable/arrivals";
};

export type PostApiV1TimetableArrivalsErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1TimetableArrivalsError = PostApiV1TimetableArrivalsErrors[keyof PostApiV1TimetableArrivalsErrors];

export type PostApiV1TimetableArrivalsResponses = {
	/**
	 * OK
	 */
	200: Array<TimetableArrival>;
};

export type PostApiV1TimetableArrivalsResponse = PostApiV1TimetableArrivalsResponses[keyof PostApiV1TimetableArrivalsResponses];
