// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5019/' | (string & {});
};

export type ArrivalDepartureComparisonItem = {
    /**
     * Arrival or departure schedule type.
     */
    scheduleType: ScheduleType;
    /**
     * Aggregated event metrics for the schedule type.
     */
    eventMetrics: EventMetrics;
};

export type BaseStation = {
    evaNumber: number | string;
    name: string;
    position: StationPosition;
};

export type EventHeatmapCell = {
    /**
     * ISO weekday number, Monday is 1 and Sunday is 7.
     */
    weekday: number | string;
    /**
     * Hour of day in Europe/Berlin.
     */
    hour: number | string;
    /**
     * Aggregated event metrics for the weekday-hour cell.
     */
    eventMetrics: EventMetrics;
};

export type EventMetrics = {
    /**
     * Number of planned stop events.
     */
    plannedEvents: number | string;
    /**
     * Number of stop events that were cancelled.
     */
    cancelledEvents: number | string;
    /**
     * Number of stop events that were not cancelled.
     */
    servedEvents: number | string;
    /**
     * Share of planned stop events that were cancelled.
     */
    cancellationRate: null | number | string;
    /**
     * Share of served stop events with less than six minutes delay.
     */
    operativePunctuality5Rate: null | number | string;
    /**
     * Share of planned stop events that were served with less than six minutes delay.
     */
    customerReliability5Rate: null | number | string;
    /**
     * Share of served stop events with less than fifteen minutes delay.
     */
    operativePunctuality15Rate: null | number | string;
    /**
     * Share of planned stop events that were served with less than fifteen minutes delay.
     */
    customerReliability15Rate: null | number | string;
    /**
     * Average delay in seconds across served stop events.
     */
    averageDelaySeconds: null | number | string;
    /**
     * Sum of positive stop-event delays in minutes.
     */
    delayDebtMinutes: number | string;
    /**
     * Share of planned stop events delayed by at least thirty minutes.
     */
    late30Rate: null | number | string;
    /**
     * Share of planned stop events delayed by at least sixty minutes.
     */
    late60Rate: null | number | string;
};

export type EventTimeSeriesPoint = {
    /**
     * Start of the returned time bucket in Europe/Berlin.
     */
    bucketStart: string;
    /**
     * Aggregated event metrics for the bucket.
     */
    eventMetrics: EventMetrics;
};

export type GeoJsonFeature = {
    /**
     * GeoJSON object type. Always Feature.
     */
    type: string;
    /**
     * Stable feature identifier.
     */
    id: string;
    /**
     * Feature geometry.
     */
    geometry: GeoJsonPoint;
    /**
     * Application-specific feature properties.
     */
    properties: {
        [key: string]: unknown;
    };
};

export type GeoJsonFeatureCollection = {
    /**
     * GeoJSON object type. Always FeatureCollection.
     */
    type: string;
    /**
     * GeoJSON features contained in the collection.
     */
    features: Array<GeoJsonFeature>;
};

export type GeoJsonPoint = {
    /**
     * GeoJSON geometry type. Always Point.
     */
    type: string;
    /**
     * Point coordinates in longitude-latitude order.
     */
    coordinates: Array<number | string>;
};

export type Journey = {
    journeyId: string;
    administration: JourneyAdministration;
    type: JourneyType;
    transport: JourneyTransport;
    continuationBy?: null | Array<string>;
    continuationFor?: null | Array<string>;
    cancelled: boolean;
    destination: JourneyRichStopPlace;
    differingDestination?: null | JourneyStopPlace;
    origin: JourneyRichStopPlace;
    differingOrigin?: null | JourneyStopPlace;
    scheduledEvents: Array<JourneyScheduledEvent>;
    messages: Array<JourneyMessage>;
};

export type JourneyAdministration = {
    administrationId: string;
    operatorCode: string;
    operatorName: string;
};

export type JourneyCalendarItem = {
    /**
     * Service date represented by the row.
     */
    serviceDate: string;
    /**
     * Destination punctuality status for the service date.
     */
    status: string;
    /**
     * Destination delay in seconds, if available.
     */
    destinationDelaySeconds: null | number | string;
    /**
     * Derived journey outcome for the service date.
     */
    outcome: string;
};

export type JourneyDailyOutcomeItem = {
    /**
     * Service date represented by the row.
     */
    serviceDate: string;
    /**
     * Derived journey outcome for the service date.
     */
    outcome: string;
    /**
     * Destination delay in seconds, if available.
     */
    destinationDelaySeconds: null | number | string;
    /**
     * Punctuality class derived from the destination delay.
     */
    destinationPunctualityClass: string;
    /**
     * Whether the journey was fully cancelled.
     */
    fullyCancelled: boolean;
    /**
     * Whether the journey was partially cancelled.
     */
    partiallyCancelled: boolean;
    /**
     * Whether the destination stop was not reached.
     */
    destinationNotReached: boolean;
};

export type JourneyDelayBuildUpItem = {
    /**
     * Station represented by the delay build-up row.
     */
    station: StationReference;
    /**
     * Median stop-event delay in seconds.
     */
    medianDelaySeconds: null | number | string;
    /**
     * 95th percentile stop-event delay in seconds.
     */
    p95DelaySeconds: null | number | string;
};

export type JourneyHeatmapCell = {
    /**
     * ISO weekday number, Monday is 1 and Sunday is 7.
     */
    weekday: number | string;
    /**
     * Hour of day in Europe/Berlin.
     */
    hour: number | string;
    /**
     * Aggregated journey metrics for the weekday-hour cell.
     */
    journeyMetrics: JourneyMetrics;
};

export type JourneyMessage = ({
    type?: 'ATTRIBUTE';
} & JourneyMessageAttributeMessage) | ({
    type?: 'DISRUPTION';
} & JourneyMessageDisruptionMessage) | ({
    type?: 'NOTE';
} & JourneyMessageNoteMessage) | ({
    type?: 'RIS_CAUSE';
} & JourneyMessageRisCauseMessage) | ({
    type?: 'RIS_QUALITY_DEVIATION';
} & JourneyMessageRisQualityDeviationMessage);

export type JourneyMessageAttributeMessage = {
    type?: TypeEnum;
    messageId: number | string;
    key: MessageKey;
    text: string;
};

export type JourneyMessageDisruptionMessage = {
    type?: TypeEnum2;
    cause?: null | string;
    effect?: null | string;
    disruptionId?: null | string;
    textShort?: null | string;
    messageId: number | string;
    key: MessageKey;
    text: string;
};

export type JourneyMessageNoteMessage = {
    type?: TypeEnum3;
    category?: null | string;
    textShort?: null | string;
    messageId: number | string;
    key: MessageKey;
    text: string;
};

export type JourneyMessageRisCauseMessage = {
    type?: TypeEnum4;
    messageId: number | string;
    key: MessageKey;
    text: string;
};

export type JourneyMessageRisQualityDeviationMessage = {
    type?: TypeEnum5;
    messageId: number | string;
    key: MessageKey;
    text: string;
};

export type JourneyMetrics = {
    /**
     * Number of planned journeys.
     */
    plannedJourneys: number | string;
    /**
     * Number of journeys that were not fully cancelled and reached the destination.
     */
    completedJourneys: number | string;
    /**
     * Number of journeys where all stop events were cancelled.
     */
    fullyCancelledJourneys: number | string;
    /**
     * Number of journeys with at least one cancelled stop event, but not fully cancelled.
     */
    partiallyCancelledJourneys: number | string;
    /**
     * Number of journeys whose destination stop was not reached.
     */
    destinationNotReachedJourneys: number | string;
    /**
     * Share of planned journeys that were fully cancelled.
     */
    fullCancellationRate: null | number | string;
    /**
     * Share of planned journeys that were partially cancelled.
     */
    partialCancellationRate: null | number | string;
    /**
     * Share of planned journeys whose destination stop was not reached.
     */
    destinationNotReachedRate: null | number | string;
    /**
     * Share of planned journeys that reached the destination and were not fully cancelled.
     */
    journeyCompletionRate: null | number | string;
    /**
     * Share of planned journeys whose destination delay was below six minutes.
     */
    destinationPunctuality5Rate: null | number | string;
    /**
     * Share of planned journeys whose destination delay was below fifteen minutes.
     */
    destinationPunctuality15Rate: null | number | string;
    /**
     * Average destination delay in seconds for journeys with a destination delay sample.
     */
    averageDestinationDelaySeconds: null | number | string;
    /**
     * Sum of positive destination delays in minutes.
     */
    destinationDelayDebtMinutes: number | string;
};

export type JourneyNumberRankingItem = {
    /**
     * Journey number represented by the row.
     */
    journeyNumber: number | string;
    /**
     * Line and route reference for the journey number.
     */
    line: LineReference;
    /**
     * Aggregated journey metrics for the journey number.
     */
    journeyMetrics: JourneyMetrics;
};

export type JourneyRichStopPlace = {
    cancelled: boolean;
    name: string;
    evaNumber: number | string;
};

export type JourneyScheduledEvent = {
    stopPlace: JourneyStopPlace;
    differingStopPlace: JourneyStopPlace;
    cancelled: boolean;
    additional: boolean;
    noPassengerChange: boolean;
    demand: boolean;
    scheduleType: ScheduleType;
    plannedTime: string;
    actualTime: string;
    delay: number | string;
    plannedPlatform?: null | string;
    actualPlatform?: null | string;
    timeType: TimeType;
    travelsWith?: null | Array<string>;
    messageIds?: null | Array<number | string>;
};

export type JourneyStatisticsMetricRequest = ({
    type?: 'PATTERN';
} & JourneyStatisticsMetricRequestJourneyPatternRequest) | ({
    type?: 'JOURNEY_KPIS';
} & JourneyStatisticsMetricRequestJourneyKpisRequest) | ({
    type?: 'DAILY_OUTCOMES';
} & JourneyStatisticsMetricRequestJourneyDailyOutcomesRequest) | ({
    type?: 'STOP_PROFILE';
} & JourneyStatisticsMetricRequestJourneyStopProfileRequest) | ({
    type?: 'DELAY_BUILD_UP';
} & JourneyStatisticsMetricRequestJourneyDelayBuildUpRequest) | ({
    type?: 'CALENDAR';
} & JourneyStatisticsMetricRequestJourneyCalendarRequest);

export type JourneyStatisticsMetricRequestJourneyCalendarRequest = {
    type?: TypeEnum6;
    /**
     * Journey number to evaluate.
     */
    journeyNumber: number | string;
    /**
     * Optional line or journey description filter.
     */
    lineName?: null | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type JourneyStatisticsMetricRequestJourneyDailyOutcomesRequest = {
    type?: TypeEnum7;
    /**
     * Journey number to evaluate.
     */
    journeyNumber: number | string;
    /**
     * Optional line or journey description filter.
     */
    lineName?: null | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type JourneyStatisticsMetricRequestJourneyDelayBuildUpRequest = {
    type?: TypeEnum8;
    scheduleType?: null | ScheduleType;
    /**
     * Journey number to evaluate.
     */
    journeyNumber: number | string;
    /**
     * Optional line or journey description filter.
     */
    lineName?: null | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type JourneyStatisticsMetricRequestJourneyKpisRequest = {
    type?: TypeEnum9;
    /**
     * Journey number to evaluate.
     */
    journeyNumber: number | string;
    /**
     * Optional line or journey description filter.
     */
    lineName?: null | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type JourneyStatisticsMetricRequestJourneyPatternRequest = {
    type?: TypeEnum10;
    /**
     * Journey number to evaluate.
     */
    journeyNumber: number | string;
    /**
     * Optional line or journey description filter.
     */
    lineName?: null | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type JourneyStatisticsMetricRequestJourneyStopProfileRequest = {
    type?: TypeEnum11;
    scheduleType?: null | ScheduleType;
    /**
     * Journey number to evaluate.
     */
    journeyNumber: number | string;
    /**
     * Optional line or journey description filter.
     */
    lineName?: null | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type JourneyStopPlace = {
    name: string;
    evaNumber: number | string;
};

export type JourneyStopProfileItem = {
    /**
     * Station represented by the stop profile row.
     */
    station: StationReference;
    /**
     * Typical planned stop time in Europe/Berlin local time.
     */
    plannedTime: string;
    /**
     * Arrival or departure schedule type.
     */
    scheduleType: ScheduleType;
    /**
     * Number of planned stop events at this stop.
     */
    plannedEvents: number | string;
    /**
     * Number of cancelled stop events at this stop.
     */
    cancelledEvents: number | string;
    /**
     * Share of planned stop events that were served with less than six minutes delay.
     */
    customerReliability5Rate: null | number | string;
    /**
     * Median stop-event delay in seconds.
     */
    medianDelaySeconds: null | number | string;
    /**
     * 95th percentile stop-event delay in seconds.
     */
    p95DelaySeconds: null | number | string;
};

export type JourneyTimeSeriesPoint = {
    /**
     * Start of the returned time bucket in Europe/Berlin.
     */
    bucketStart: string;
    /**
     * Aggregated journey metrics for the bucket.
     */
    journeyMetrics: JourneyMetrics;
};

export type JourneyTransport = {
    type: TransportType;
    replacementType?: null | TransportType;
    category?: null | string;
    categoryInternal?: null | string;
    journeyDescription: string;
    label?: null | string;
    line?: null | string;
    number: number | string;
};

export enum JourneyType {
    REGULAR = 'REGULAR',
    REPLACEMENT = 'REPLACEMENT',
    RELIEF = 'RELIEF',
    EXTRA = 'EXTRA'
}

export type LineHourMatrixItem = {
    /**
     * Line or journey description.
     */
    lineName: string;
    /**
     * Transport type of the line.
     */
    transportType: TransportType;
    /**
     * Hour of day in Europe/Berlin.
     */
    hour: number | string;
    /**
     * Aggregated event metrics for the line-hour cell.
     */
    eventMetrics: EventMetrics;
};

export type LineJourneyRankingItem = {
    /**
     * Ranked line or route.
     */
    line: LineReference;
    /**
     * Aggregated journey metrics for the line.
     */
    journeyMetrics: JourneyMetrics;
};

export type LineReference = {
    /**
     * Line or journey description.
     */
    lineName: string;
    /**
     * Journey number if the row represents a concrete journey number.
     */
    journeyNumber: null | number | string;
    /**
     * Transport type of the line.
     */
    transportType: TransportType;
    origin: null | StationReference;
    destination: null | StationReference;
};

export type LineStationPerformanceItem = {
    /**
     * Station on the line.
     */
    station: StationReference;
    /**
     * Aggregated event metrics for the line at this station.
     */
    eventMetrics: EventMetrics;
};

export type LineStatisticsMetricRequest = ({
    type?: 'SUMMARY';
} & LineStatisticsMetricRequestLineSummaryRequest) | ({
    type?: 'JOURNEY_KPIS';
} & LineStatisticsMetricRequestLineJourneyKpisRequest) | ({
    type?: 'EVENT_KPIS';
} & LineStatisticsMetricRequestLineEventKpisRequest) | ({
    type?: 'TIME_SERIES';
} & LineStatisticsMetricRequestLineTimeSeriesRequest) | ({
    type?: 'ROUTE_VARIANTS';
} & LineStatisticsMetricRequestLineRouteVariantsRequest) | ({
    type?: 'STATION_PERFORMANCE';
} & LineStatisticsMetricRequestLineStationPerformanceRequest) | ({
    type?: 'JOURNEY_NUMBER_RANKING';
} & LineStatisticsMetricRequestLineJourneyNumberRankingRequest) | ({
    type?: 'WEEKDAY_HOUR_HEATMAP';
} & LineStatisticsMetricRequestLineWeekdayHourHeatmapRequest) | ({
    type?: 'PROBLEM_STATIONS';
} & LineStatisticsMetricRequestLineProblemStationsRequest);

export type LineStatisticsMetricRequestLineEventKpisRequest = {
    type?: TypeEnum12;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineJourneyKpisRequest = {
    type?: TypeEnum9;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineJourneyNumberRankingRequest = {
    type?: TypeEnum13;
    /**
     * Minimum planned journey count required for a journey number to be included.
     */
    minVolume?: number | string;
    /**
     * Maximum number of journey numbers to return.
     */
    limit?: number | string;
    /**
     * Number of journey numbers to skip.
     */
    offset?: number | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineProblemStationsRequest = {
    type?: TypeEnum14;
    /**
     * Minimum planned event count required for a station to be included.
     */
    minVolume?: number | string;
    /**
     * Maximum number of stations to return.
     */
    limit?: number | string;
    /**
     * Number of stations to skip.
     */
    offset?: number | string;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineRouteVariantsRequest = {
    type?: TypeEnum15;
    /**
     * Minimum planned journey count required for a route variant to be included.
     */
    minVolume?: number | string;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineStationPerformanceRequest = {
    type?: TypeEnum16;
    /**
     * Minimum planned event count required for a station to be included.
     */
    minVolume?: number | string;
    /**
     * Maximum number of stations to return.
     */
    limit?: number | string;
    /**
     * Number of stations to skip.
     */
    offset?: number | string;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineSummaryRequest = {
    type?: TypeEnum17;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineTimeSeriesRequest = {
    type?: TypeEnum18;
    /**
     * Aggregation bucket used for returned time series.
     */
    bucket?: StatisticsBucket;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineStatisticsMetricRequestLineWeekdayHourHeatmapRequest = {
    type?: TypeEnum19;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Line or journey description to evaluate.
     */
    lineName: string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type LineTimeSeriesPoint = {
    /**
     * Start of the returned time bucket in Europe/Berlin.
     */
    bucketStart: string;
    /**
     * Aggregated journey metrics for the bucket.
     */
    journeyMetrics: JourneyMetrics;
    /**
     * Aggregated event metrics for the bucket.
     */
    eventMetrics: EventMetrics;
};

export enum MessageKey {
    UNPLANNED_INFO = 'UNPLANNED_INFO',
    GENERAL_WARNING = 'GENERAL_WARNING',
    ADDITIONAL_COACHES = 'ADDITIONAL_COACHES',
    MISSING_COACHES = 'MISSING_COACHES',
    CHANGED_COACH_SEQUENCE = 'CHANGED_COACH_SEQUENCE',
    REPLACEMENT_SERVICE = 'REPLACEMENT_SERVICE',
    ADDITIONAL_STOP = 'ADDITIONAL_STOP',
    WIFI_DISTRIBUTION = 'WIFI_DISTRIBUTION',
    NO_FIRST_CLASS = 'NO_FIRST_CLASS',
    ACCESSIBILITY_WARNING = 'ACCESSIBILITY_WARNING',
    RESERVATIONS_MISSING = 'RESERVATIONS_MISSING',
    RESERVATIONS_REQUIRED = 'RESERVATIONS_REQUIRED',
    NO_FOOD = 'NO_FOOD',
    BICYCLE_WARNING = 'BICYCLE_WARNING',
    BICYCLE_TRANSPORT = 'BICYCLE_TRANSPORT',
    BICYCLE_TRANSPORT_NOT_POSSIBLE = 'BICYCLE_TRANSPORT_NOT_POSSIBLE',
    BICYCLE_RESERVATION_REQUIRED = 'BICYCLE_RESERVATION_REQUIRED',
    TICKET_INFORMATION = 'TICKET_INFORMATION'
}

export enum MessageType {
    ATTRIBUTE = 'ATTRIBUTE',
    DISRUPTION = 'DISRUPTION',
    NOTE = 'NOTE',
    RIS_CAUSE = 'RIS_CAUSE',
    RIS_QUALITY_DEVIATION = 'RIS_QUALITY_DEVIATION'
}

export type MetricPage = {
    /**
     * Number of skipped items.
     */
    offset: number | string;
    /**
     * Maximum number of returned items.
     */
    limit: number | string;
    /**
     * Total number of matching items before paging.
     */
    totalItems: number | string;
};

export type NetworkMapHotspotsRequest = {
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Minimum planned event count required for a station to be included.
     */
    minVolume?: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequest = ({
    type?: 'EVENT_KPIS';
} & NetworkStatisticsMetricRequestNetworkEventKpisRequest) | ({
    type?: 'JOURNEY_KPIS';
} & NetworkStatisticsMetricRequestNetworkJourneyKpisRequest) | ({
    type?: 'EVENT_TIME_SERIES';
} & NetworkStatisticsMetricRequestNetworkEventTimeSeriesRequest) | ({
    type?: 'JOURNEY_TIME_SERIES';
} & NetworkStatisticsMetricRequestNetworkJourneyTimeSeriesRequest) | ({
    type?: 'WEEKDAY_HOUR_HEATMAP';
} & NetworkStatisticsMetricRequestNetworkWeekdayHourHeatmapRequest) | ({
    type?: 'TRANSPORT_TYPE_COMPARISON';
} & NetworkStatisticsMetricRequestNetworkTransportTypeComparisonRequest) | ({
    type?: 'STATION_RANKING';
} & NetworkStatisticsMetricRequestNetworkStationRankingRequest) | ({
    type?: 'LINE_RANKING';
} & NetworkStatisticsMetricRequestNetworkLineRankingRequest);

export type NetworkStatisticsMetricRequestNetworkEventKpisRequest = {
    type?: TypeEnum12;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequestNetworkEventTimeSeriesRequest = {
    type?: TypeEnum20;
    /**
     * Aggregation bucket used for returned time series.
     */
    bucket?: StatisticsBucket;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequestNetworkJourneyKpisRequest = {
    type?: TypeEnum9;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequestNetworkJourneyTimeSeriesRequest = {
    type?: TypeEnum21;
    /**
     * Aggregation bucket used for returned time series.
     */
    bucket?: StatisticsBucket;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequestNetworkLineRankingRequest = {
    type?: TypeEnum22;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Minimum planned journey count required for a line to be included.
     */
    minVolume?: number | string;
    /**
     * Maximum number of lines to return.
     */
    limit?: number | string;
    /**
     * Number of lines to skip.
     */
    offset?: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequestNetworkStationRankingRequest = {
    type?: TypeEnum23;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Minimum planned event count required for a station to be included.
     */
    minVolume?: number | string;
    /**
     * Maximum number of stations to return.
     */
    limit?: number | string;
    /**
     * Number of stations to skip.
     */
    offset?: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequestNetworkTransportTypeComparisonRequest = {
    type?: TypeEnum24;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type NetworkStatisticsMetricRequestNetworkWeekdayHourHeatmapRequest = {
    type?: TypeEnum19;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type RouteVariantItem = {
    /**
     * Stable key for the origin-destination variant.
     */
    variantKey: string;
    /**
     * Origin station of the variant.
     */
    origin: StationReference;
    /**
     * Destination station of the variant.
     */
    destination: StationReference;
    /**
     * Transport type of the variant.
     */
    transportType: TransportType;
    /**
     * Aggregated journey metrics for the variant.
     */
    journeyMetrics: JourneyMetrics;
};

export enum ScheduleType {
    ARRIVAL = 'ARRIVAL',
    DEPARTURE = 'DEPARTURE'
}

export type Station = {
    transports: Array<TransportType>;
    ril100?: null | Array<string>;
    evaNumber: number | string;
    name: string;
    position: StationPosition;
};

/**
 * Represents a request to find stations near specific geographic coordinates.
 */
export type StationByGeographicCoordinatesRequest = {
    /**
     * The latitude of the location.
     */
    latitude: number | string;
    /**
     * The longitude of the location.
     */
    longitude: number | string;
    /**
     * The maximum number of stations to return. Defaults to 100.
     */
    limit?: null | number | string;
    /**
     * The maximum distance in meters to search for stations. Defaults to 1000.
     */
    maxDistance?: null | number | string;
};

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location types.
 */
export type StationBySerchtermRequest = {
    /**
     * The term to search for in station names or codes.
     */
    searchTerm: string;
    /**
     * The maximum number of results to return. Defaults to 10 if not specified.
     */
    maxResults?: null | number | string;
    /**
     * An array of location types to filter the search results. Defaults to ['ALL'] if not specified.
     */
    locationTypes?: null | Array<string>;
};

export type StationDirectionItem = {
    /**
     * Whether the connected station is treated as origin or destination.
     */
    directionType: string;
    /**
     * Connected station.
     */
    station: StationReference;
    /**
     * Aggregated event metrics for the direction.
     */
    eventMetrics: EventMetrics;
};

export type StationEventDetailItem = {
    /**
     * Internal stop-place identifier.
     */
    stopPlaceId: string;
    /**
     * External journey identifier from the source data.
     */
    journeyId: string;
    /**
     * Service date of the journey.
     */
    journeyDate: string;
    /**
     * Station EVA number of the stop event.
     */
    stationEvaNumber: number | string;
    /**
     * Planned stop-event time in UTC.
     */
    plannedTime: string;
    /**
     * Arrival or departure schedule type of the stop event.
     */
    scheduleType: ScheduleType;
    /**
     * Journey number.
     */
    journeyNumber: number | string;
    /**
     * Line or journey description.
     */
    lineName: string;
    /**
     * Origin station EVA number of the journey.
     */
    originEvaNumber: number | string;
    /**
     * Planned journey start time in UTC.
     */
    journeyStartTime: string;
    /**
     * Destination station EVA number of the journey.
     */
    destinationEvaNumber: number | string;
    /**
     * Planned journey end time in UTC.
     */
    journeyEndTime: string;
    /**
     * Whether this stop event was cancelled.
     */
    stopCancelled: boolean;
    /**
     * Transport type of the journey.
     */
    transportType: TransportType;
    /**
     * Stop-event delay in seconds.
     */
    eventDelaySeconds: number | string;
    /**
     * Whether the journey is replacement transport.
     */
    isReplacement: boolean;
};

export type StationEventRankingItem = {
    /**
     * Ranked station.
     */
    station: StationReference;
    /**
     * Aggregated event metrics for the station.
     */
    eventMetrics: EventMetrics;
};

export type StationGatheringInfo = {
    queryingEnabled: boolean;
    lastQueried?: null | string;
    active: Array<TransportType>;
    disabled: Array<TransportType>;
};

export type StationLineRankingItem = {
    /**
     * Ranked line at the station.
     */
    line: LineReference;
    /**
     * Aggregated event metrics for the station-line combination.
     */
    eventMetrics: EventMetrics;
};

export type StationPosition = {
    latitude: number | string;
    longitude: number | string;
};

export type StationReference = {
    /**
     * Station EVA number.
     */
    stationEvaNumber: number | string;
    /**
     * Station display name if available.
     */
    stationName?: null | string;
    /**
     * Station latitude if available.
     */
    latitude?: null | number | string;
    /**
     * Station longitude if available.
     */
    longitude?: null | number | string;
};

export type StationStatisticsMetricRequest = ({
    type?: 'EVENT_KPIS';
} & StationStatisticsMetricRequestStationEventKpisRequest) | ({
    type?: 'BENCHMARK';
} & StationStatisticsMetricRequestStationBenchmarkRequest) | ({
    type?: 'TIME_SERIES';
} & StationStatisticsMetricRequestStationTimeSeriesRequest) | ({
    type?: 'ARRIVAL_DEPARTURE_COMPARISON';
} & StationStatisticsMetricRequestStationArrivalDepartureComparisonRequest) | ({
    type?: 'WEEKDAY_HOUR_HEATMAP';
} & StationStatisticsMetricRequestStationWeekdayHourHeatmapRequest) | ({
    type?: 'LINE_RANKING';
} & StationStatisticsMetricRequestStationLineRankingRequest) | ({
    type?: 'DIRECTIONS';
} & StationStatisticsMetricRequestStationDirectionsRequest) | ({
    type?: 'TRANSPORT_TYPE_MIX';
} & StationStatisticsMetricRequestStationTransportTypeMixRequest) | ({
    type?: 'LINE_HOUR_MATRIX';
} & StationStatisticsMetricRequestStationLineHourMatrixRequest) | ({
    type?: 'EVENT_DETAILS';
} & StationStatisticsMetricRequestStationEventDetailsRequest);

export type StationStatisticsMetricRequestStationArrivalDepartureComparisonRequest = {
    type?: TypeEnum25;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationBenchmarkRequest = {
    type?: TypeEnum26;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationDirectionsRequest = {
    type?: TypeEnum27;
    /**
     * Optional connected station EVA number filter.
     */
    directionEvaNumber?: null | number | string;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationEventDetailsRequest = {
    type?: TypeEnum28;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional journey number filter.
     */
    journeyNumber?: null | number | string;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Maximum number of detail rows to return.
     */
    limit?: number | string;
    /**
     * Number of detail rows to skip.
     */
    offset?: number | string;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationEventKpisRequest = {
    type?: TypeEnum12;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationLineHourMatrixRequest = {
    type?: TypeEnum29;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Optional connected station EVA number filter.
     */
    directionEvaNumber?: null | number | string;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationLineRankingRequest = {
    type?: TypeEnum22;
    /**
     * Optional origin station EVA number filter.
     */
    originEvaNumber?: null | number | string;
    /**
     * Optional destination station EVA number filter.
     */
    destinationEvaNumber?: null | number | string;
    /**
     * Optional connected station EVA number filter.
     */
    directionEvaNumber?: null | number | string;
    /**
     * Minimum planned event count required for a line to be included.
     */
    minVolume?: number | string;
    /**
     * Maximum number of ranked lines to return.
     */
    limit?: number | string;
    /**
     * Number of ranked lines to skip.
     */
    offset?: number | string;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationTimeSeriesRequest = {
    type?: TypeEnum18;
    /**
     * Aggregation bucket used for returned time series.
     */
    bucket?: StatisticsBucket;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationTransportTypeMixRequest = {
    type?: TypeEnum30;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export type StationStatisticsMetricRequestStationWeekdayHourHeatmapRequest = {
    type?: TypeEnum19;
    scheduleType?: null | ScheduleType;
    /**
     * Optional transport types to include. Empty means all transport types.
     */
    transportTypes?: Array<TransportType>;
    /**
     * Optional external administration identifiers to include.
     */
    administrationIds?: Array<string>;
    /**
     * Whether replacement transport should be included.
     */
    includeReplacement?: boolean;
    /**
     * Station EVA number to evaluate.
     */
    stationEvaNumber: number | string;
    /**
     * First local service day to include. The date is interpreted in Europe/Berlin.
     */
    from: string;
    /**
     * First local service day to exclude. The date is interpreted in Europe/Berlin.
     */
    to: string;
};

export enum StatisticsBucket {
    HOUR = 'HOUR',
    DAY = 'DAY',
    WEEK = 'WEEK',
    MONTH = 'MONTH'
}

export type StatisticsMetricResponse = {
    /**
     * Metadata describing the evaluated metric, time range and filters.
     */
    meta: StatisticsResponseMeta;
    /**
     * Typed metric result. The concrete shape is selected by result.type.
     */
    result: StatisticsMetricResult;
};

export type StatisticsMetricResult = ({
    type?: 'EVENT_KPIS';
} & StatisticsMetricResultEventKpisResult) | ({
    type?: 'JOURNEY_KPIS';
} & StatisticsMetricResultJourneyKpisResult) | ({
    type?: 'NETWORK_EVENT_TIME_SERIES';
} & StatisticsMetricResultNetworkEventTimeSeriesResult) | ({
    type?: 'NETWORK_JOURNEY_TIME_SERIES';
} & StatisticsMetricResultNetworkJourneyTimeSeriesResult) | ({
    type?: 'EVENT_WEEKDAY_HOUR_HEATMAP';
} & StatisticsMetricResultEventWeekdayHourHeatmapResult) | ({
    type?: 'JOURNEY_WEEKDAY_HOUR_HEATMAP';
} & StatisticsMetricResultJourneyWeekdayHourHeatmapResult) | ({
    type?: 'TRANSPORT_TYPE_COMPARISON';
} & StatisticsMetricResultTransportTypeComparisonResult) | ({
    type?: 'NETWORK_STATION_RANKING';
} & StatisticsMetricResultNetworkStationRankingResult) | ({
    type?: 'NETWORK_LINE_RANKING';
} & StatisticsMetricResultNetworkLineRankingResult) | ({
    type?: 'NETWORK_MAP_HOTSPOTS';
} & StatisticsMetricResultNetworkMapHotspotsResult) | ({
    type?: 'STATION_BENCHMARK';
} & StatisticsMetricResultStationBenchmarkResult) | ({
    type?: 'STATION_TIME_SERIES';
} & StatisticsMetricResultStationTimeSeriesResult) | ({
    type?: 'ARRIVAL_DEPARTURE_COMPARISON';
} & StatisticsMetricResultArrivalDepartureComparisonResult) | ({
    type?: 'STATION_LINE_RANKING';
} & StatisticsMetricResultStationLineRankingResult) | ({
    type?: 'STATION_DIRECTIONS';
} & StatisticsMetricResultStationDirectionsResult) | ({
    type?: 'TRANSPORT_TYPE_MIX';
} & StatisticsMetricResultTransportTypeMixResult) | ({
    type?: 'LINE_HOUR_MATRIX';
} & StatisticsMetricResultLineHourMatrixResult) | ({
    type?: 'STATION_EVENT_DETAILS';
} & StatisticsMetricResultStationEventDetailsResult) | ({
    type?: 'LINE_SUMMARY';
} & StatisticsMetricResultLineSummaryResult) | ({
    type?: 'LINE_TIME_SERIES';
} & StatisticsMetricResultLineTimeSeriesResult) | ({
    type?: 'LINE_ROUTE_VARIANTS';
} & StatisticsMetricResultLineRouteVariantsResult) | ({
    type?: 'LINE_STATION_PERFORMANCE';
} & StatisticsMetricResultLineStationPerformanceResult) | ({
    type?: 'LINE_JOURNEY_NUMBER_RANKING';
} & StatisticsMetricResultLineJourneyNumberRankingResult) | ({
    type?: 'LINE_PROBLEM_STATIONS';
} & StatisticsMetricResultLineProblemStationsResult) | ({
    type?: 'JOURNEY_PATTERN';
} & StatisticsMetricResultJourneyPatternResult) | ({
    type?: 'JOURNEY_DAILY_OUTCOMES';
} & StatisticsMetricResultJourneyDailyOutcomesResult) | ({
    type?: 'JOURNEY_STOP_PROFILE';
} & StatisticsMetricResultJourneyStopProfileResult) | ({
    type?: 'JOURNEY_DELAY_BUILD_UP';
} & StatisticsMetricResultJourneyDelayBuildUpResult) | ({
    type?: 'JOURNEY_CALENDAR';
} & StatisticsMetricResultJourneyCalendarResult);

export type StatisticsMetricResultArrivalDepartureComparisonResult = {
    type?: TypeEnum25;
    /**
     * Event metrics grouped by arrival and departure schedule type.
     */
    items: Array<ArrivalDepartureComparisonItem>;
};

export type StatisticsMetricResultEventKpisResult = {
    type?: TypeEnum12;
    /**
     * Event quality KPIs.
     */
    metrics: EventMetrics;
};

export type StatisticsMetricResultEventWeekdayHourHeatmapResult = {
    type?: TypeEnum31;
    /**
     * Event metric cells grouped by weekday and hour.
     */
    items: Array<EventHeatmapCell>;
};

export type StatisticsMetricResultJourneyCalendarResult = {
    type?: TypeEnum32;
    /**
     * Calendar rows for the journey number.
     */
    items: Array<JourneyCalendarItem>;
};

export type StatisticsMetricResultJourneyDailyOutcomesResult = {
    type?: TypeEnum33;
    /**
     * Daily outcomes for the journey number.
     */
    items: Array<JourneyDailyOutcomeItem>;
};

export type StatisticsMetricResultJourneyDelayBuildUpResult = {
    type?: TypeEnum34;
    /**
     * Delay distribution along the journey stops.
     */
    items: Array<JourneyDelayBuildUpItem>;
};

export type StatisticsMetricResultJourneyKpisResult = {
    type?: TypeEnum9;
    /**
     * Journey quality KPIs.
     */
    metrics: JourneyMetrics;
};

export type StatisticsMetricResultJourneyPatternResult = {
    type?: TypeEnum35;
    /**
     * Journey number represented by the pattern.
     */
    journeyNumber: number | string;
    /**
     * Line or journey description if available.
     */
    lineName: null | string;
    transportType: null | TransportType;
    /**
     * Typical scheduled start time in Europe/Berlin local time.
     */
    scheduledStartTime: string;
    /**
     * Typical scheduled end time in Europe/Berlin local time.
     */
    scheduledEndTime: string;
    mainOrigin: null | StationReference;
    mainDestination: null | StationReference;
    /**
     * Number of service days observed in the selected range.
     */
    observedServiceDays: number | string;
    /**
     * Number of observed origin-destination variants.
     */
    routeVariantCount: number | string;
};

export type StatisticsMetricResultJourneyStopProfileResult = {
    type?: TypeEnum36;
    /**
     * Stop profile rows for the journey number.
     */
    items: Array<JourneyStopProfileItem>;
};

export type StatisticsMetricResultJourneyWeekdayHourHeatmapResult = {
    type?: TypeEnum37;
    /**
     * Journey metric cells grouped by weekday and hour.
     */
    items: Array<JourneyHeatmapCell>;
};

export type StatisticsMetricResultLineHourMatrixResult = {
    type?: TypeEnum29;
    /**
     * Station-line event metrics grouped by hour.
     */
    items: Array<LineHourMatrixItem>;
};

export type StatisticsMetricResultLineJourneyNumberRankingResult = {
    type?: TypeEnum38;
    /**
     * Journey numbers ranked within the line.
     */
    items: Array<JourneyNumberRankingItem>;
    /**
     * Paging metadata for the ranking.
     */
    page: MetricPage;
};

export type StatisticsMetricResultLineProblemStationsResult = {
    type?: TypeEnum39;
    /**
     * Stations with the highest delay impact for the line.
     */
    items: Array<LineStationPerformanceItem>;
    /**
     * Paging metadata for the station rows.
     */
    page: MetricPage;
};

export type StatisticsMetricResultLineRouteVariantsResult = {
    type?: TypeEnum40;
    /**
     * Observed origin-destination variants for the line.
     */
    items: Array<RouteVariantItem>;
};

export type StatisticsMetricResultLineStationPerformanceResult = {
    type?: TypeEnum41;
    /**
     * Station performance rows for the line.
     */
    items: Array<LineStationPerformanceItem>;
    /**
     * Paging metadata for the station rows.
     */
    page: MetricPage;
};

export type StatisticsMetricResultLineSummaryResult = {
    type?: TypeEnum42;
    /**
     * Line or journey description.
     */
    lineName: string;
    transportType: null | TransportType;
    /**
     * Most frequently observed journey numbers for the line.
     */
    representativeJourneyNumbers: Array<number | string>;
    /**
     * Number of observed origin-destination variants.
     */
    routeVariantCount: number | string;
    mainOrigin: null | StationReference;
    mainDestination: null | StationReference;
};

export type StatisticsMetricResultLineTimeSeriesResult = {
    type?: TypeEnum43;
    /**
     * Line metric points grouped by the requested bucket.
     */
    items: Array<LineTimeSeriesPoint>;
};

export type StatisticsMetricResultNetworkEventTimeSeriesResult = {
    type?: TypeEnum44;
    /**
     * Event metric points grouped by the requested bucket.
     */
    items: Array<EventTimeSeriesPoint>;
};

export type StatisticsMetricResultNetworkJourneyTimeSeriesResult = {
    type?: TypeEnum45;
    /**
     * Journey metric points grouped by the requested bucket.
     */
    items: Array<JourneyTimeSeriesPoint>;
};

export type StatisticsMetricResultNetworkLineRankingResult = {
    type?: TypeEnum46;
    /**
     * Ranked lines.
     */
    items: Array<LineJourneyRankingItem>;
    /**
     * Paging metadata for the ranking.
     */
    page: MetricPage;
};

export type StatisticsMetricResultNetworkMapHotspotsResult = {
    type?: TypeEnum47;
    /**
     * GeoJSON feature collection for station hotspots.
     */
    featureCollection: GeoJsonFeatureCollection;
};

export type StatisticsMetricResultNetworkStationRankingResult = {
    type?: TypeEnum48;
    /**
     * Ranked stations.
     */
    items: Array<StationEventRankingItem>;
    /**
     * Paging metadata for the ranking.
     */
    page: MetricPage;
};

export type StatisticsMetricResultStationBenchmarkResult = {
    type?: TypeEnum49;
    /**
     * Event metrics for the requested station.
     */
    station: EventMetrics;
    /**
     * Comparable event metrics for the filtered network.
     */
    network: EventMetrics;
    /**
     * Optional benchmark stations with similar characteristics.
     */
    similarStations: null | Array<StationEventRankingItem>;
};

export type StatisticsMetricResultStationDirectionsResult = {
    type?: TypeEnum50;
    /**
     * Connected origin and destination directions for the station.
     */
    items: Array<StationDirectionItem>;
};

export type StatisticsMetricResultStationEventDetailsResult = {
    type?: TypeEnum51;
    /**
     * Detailed stop events at the station.
     */
    items: Array<StationEventDetailItem>;
    /**
     * Paging metadata for the detail rows.
     */
    page: MetricPage;
};

export type StatisticsMetricResultStationLineRankingResult = {
    type?: TypeEnum52;
    /**
     * Ranked lines observed at the station.
     */
    items: Array<StationLineRankingItem>;
    /**
     * Paging metadata for the ranking.
     */
    page: MetricPage;
};

export type StatisticsMetricResultStationTimeSeriesResult = {
    type?: TypeEnum53;
    /**
     * Station event metric points grouped by the requested bucket.
     */
    items: Array<EventTimeSeriesPoint>;
};

export type StatisticsMetricResultTransportTypeComparisonResult = {
    type?: TypeEnum24;
    /**
     * Event and journey metrics grouped by transport type.
     */
    items: Array<TransportTypeComparisonItem>;
};

export type StatisticsMetricResultTransportTypeMixResult = {
    type?: TypeEnum30;
    /**
     * Station event metrics grouped by transport type.
     */
    items: Array<TransportTypeMixItem>;
};

export type StatisticsResponseMeta = {
    /**
     * Statistics topic that produced the metric.
     */
    scope: string;
    /**
     * Metric name that was evaluated.
     */
    metric: string;
    /**
     * First included local service day.
     */
    from: string;
    /**
     * First excluded local service day.
     */
    to: string;
    /**
     * Aggregation bucket used for grouped results.
     */
    bucket: StatisticsBucket;
    /**
     * Timezone used to interpret service days and buckets.
     */
    timezone: string;
    /**
     * Effective filters applied to the metric.
     */
    filters: {
        [key: string]: unknown;
    };
};

export type TimetableArrival = {
    journeyId: string;
    administration: TimetableEntryAdministration;
    transport: TimetableEntryTransport;
    origin: TimetableEntryRichStopPlace;
    differingOrigin?: null | TimetableEntryRichStopPlace;
    direction: Array<TimetableEntryStopPlace>;
    viaStops: Array<TimetableEntryRichStopPlace>;
    schedule: TimetableEntrySchedule;
    messages: Array<TimetableEntryMessage>;
    cancelled: boolean;
    additional?: null | boolean;
    demand?: null | boolean;
    travelsWith?: null | Array<string>;
};

export type TimetableDeparture = {
    journeyId: string;
    administration: TimetableEntryAdministration;
    transport: TimetableEntryTransport;
    destination: TimetableEntryRichStopPlace;
    differingDestination?: null | TimetableEntryRichStopPlace;
    direction: Array<TimetableEntryStopPlace>;
    viaStops: Array<TimetableEntryRichStopPlace>;
    schedule: TimetableEntrySchedule;
    messages: Array<TimetableEntryMessage>;
    cancelled: boolean;
    additional?: null | boolean;
    demand?: null | boolean;
    travelsWith?: null | Array<TimetableEntryCoupledTransport>;
};

export type TimetableEntryAdministration = {
    administrationId: string;
    operatorCode: string;
    operatorName: string;
};

export type TimetableEntryCoupledTransport = {
    journeyId: string;
    separationAt?: null | TimetableEntryStopPlace;
};

export type TimetableEntryMessage = {
    type: MessageType;
    key: MessageKey;
    text: string;
    textShort?: null | string;
};

export type TimetableEntryRichStopPlace = {
    cancelled: boolean;
    additional?: null | boolean;
    name: string;
    evaNumber: number | string;
};

export type TimetableEntrySchedule = {
    plannedTime: string;
    actualTime: string;
    delay?: number | string;
    plannedPlatform?: null | string;
    actualPlatform?: null | string;
    timeType: TimeType;
};

export type TimetableEntryStopPlace = {
    name: string;
    evaNumber: number | string;
};

export type TimetableEntryTransport = {
    type: TransportType;
    replacementType?: null | TransportType;
    category?: null | string;
    categoryInternal?: null | string;
    journeyType: JourneyType;
    journeyDescription: string;
    number: number | string;
    line?: null | string;
};

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location types.
 */
export type TimetableRequest = {
    /**
     * The evaNumber to lookup a timetable for
     */
    evaNumber: number | string;
    /**
     * The date and time for which to retrieve the timetable. Defaults to the current date and time if not specified.
     */
    when?: null | string;
    /**
     * The duration in minutes for which to retrieve the timetable. Defaults to 60 minutes if not specified.
     */
    duration?: null | number | string;
};

export enum TimeType {
    SCHEDULE = 'SCHEDULE',
    PREVIEW = 'PREVIEW',
    REAL = 'REAL'
}

export enum TransportType {
    UNKNOWN = 'UNKNOWN',
    HIGH_SPEED_TRAIN = 'HIGH_SPEED_TRAIN',
    INTERCITY_TRAIN = 'INTERCITY_TRAIN',
    INTER_REGIONAL_TRAIN = 'INTER_REGIONAL_TRAIN',
    REGIONAL_TRAIN = 'REGIONAL_TRAIN',
    CITY_TRAIN = 'CITY_TRAIN',
    SUBWAY = 'SUBWAY',
    TRAM = 'TRAM',
    BUS = 'BUS',
    FERRY = 'FERRY',
    FLIGHT = 'FLIGHT',
    CAR = 'CAR',
    TAXI = 'TAXI',
    SHUTTLE = 'SHUTTLE',
    BIKE = 'BIKE',
    SCOOTER = 'SCOOTER',
    WALK = 'WALK'
}

export type TransportTypeComparisonItem = {
    /**
     * Transport type represented by the item.
     */
    transportType: TransportType;
    /**
     * Aggregated event metrics for the transport type.
     */
    eventMetrics: EventMetrics;
    /**
     * Aggregated journey metrics for the transport type.
     */
    journeyMetrics: JourneyMetrics;
};

export type TransportTypeMixItem = {
    /**
     * Transport type represented by the item.
     */
    transportType: TransportType;
    /**
     * Share of station events represented by this transport type.
     */
    share: null | number | string;
    /**
     * Aggregated event metrics for the transport type.
     */
    eventMetrics: EventMetrics;
};

export enum TypeEnum {
    ATTRIBUTE = 'ATTRIBUTE'
}

export enum TypeEnum2 {
    DISRUPTION = 'DISRUPTION'
}

export enum TypeEnum3 {
    NOTE = 'NOTE'
}

export enum TypeEnum4 {
    RIS_CAUSE = 'RIS_CAUSE'
}

export enum TypeEnum5 {
    RIS_QUALITY_DEVIATION = 'RIS_QUALITY_DEVIATION'
}

export enum TypeEnum6 {
    CALENDAR = 'CALENDAR'
}

export enum TypeEnum7 {
    DAILY_OUTCOMES = 'DAILY_OUTCOMES'
}

export enum TypeEnum8 {
    DELAY_BUILD_UP = 'DELAY_BUILD_UP'
}

export enum TypeEnum9 {
    JOURNEY_KPIS = 'JOURNEY_KPIS'
}

export enum TypeEnum10 {
    PATTERN = 'PATTERN'
}

export enum TypeEnum11 {
    STOP_PROFILE = 'STOP_PROFILE'
}

export enum TypeEnum12 {
    EVENT_KPIS = 'EVENT_KPIS'
}

export enum TypeEnum13 {
    JOURNEY_NUMBER_RANKING = 'JOURNEY_NUMBER_RANKING'
}

export enum TypeEnum14 {
    PROBLEM_STATIONS = 'PROBLEM_STATIONS'
}

export enum TypeEnum15 {
    ROUTE_VARIANTS = 'ROUTE_VARIANTS'
}

export enum TypeEnum16 {
    STATION_PERFORMANCE = 'STATION_PERFORMANCE'
}

export enum TypeEnum17 {
    SUMMARY = 'SUMMARY'
}

export enum TypeEnum18 {
    TIME_SERIES = 'TIME_SERIES'
}

export enum TypeEnum19 {
    WEEKDAY_HOUR_HEATMAP = 'WEEKDAY_HOUR_HEATMAP'
}

export enum TypeEnum20 {
    EVENT_TIME_SERIES = 'EVENT_TIME_SERIES'
}

export enum TypeEnum21 {
    JOURNEY_TIME_SERIES = 'JOURNEY_TIME_SERIES'
}

export enum TypeEnum22 {
    LINE_RANKING = 'LINE_RANKING'
}

export enum TypeEnum23 {
    STATION_RANKING = 'STATION_RANKING'
}

export enum TypeEnum24 {
    TRANSPORT_TYPE_COMPARISON = 'TRANSPORT_TYPE_COMPARISON'
}

export enum TypeEnum25 {
    ARRIVAL_DEPARTURE_COMPARISON = 'ARRIVAL_DEPARTURE_COMPARISON'
}

export enum TypeEnum26 {
    BENCHMARK = 'BENCHMARK'
}

export enum TypeEnum27 {
    DIRECTIONS = 'DIRECTIONS'
}

export enum TypeEnum28 {
    EVENT_DETAILS = 'EVENT_DETAILS'
}

export enum TypeEnum29 {
    LINE_HOUR_MATRIX = 'LINE_HOUR_MATRIX'
}

export enum TypeEnum30 {
    TRANSPORT_TYPE_MIX = 'TRANSPORT_TYPE_MIX'
}

export enum TypeEnum31 {
    EVENT_WEEKDAY_HOUR_HEATMAP = 'EVENT_WEEKDAY_HOUR_HEATMAP'
}

export enum TypeEnum32 {
    JOURNEY_CALENDAR = 'JOURNEY_CALENDAR'
}

export enum TypeEnum33 {
    JOURNEY_DAILY_OUTCOMES = 'JOURNEY_DAILY_OUTCOMES'
}

export enum TypeEnum34 {
    JOURNEY_DELAY_BUILD_UP = 'JOURNEY_DELAY_BUILD_UP'
}

export enum TypeEnum35 {
    JOURNEY_PATTERN = 'JOURNEY_PATTERN'
}

export enum TypeEnum36 {
    JOURNEY_STOP_PROFILE = 'JOURNEY_STOP_PROFILE'
}

export enum TypeEnum37 {
    JOURNEY_WEEKDAY_HOUR_HEATMAP = 'JOURNEY_WEEKDAY_HOUR_HEATMAP'
}

export enum TypeEnum38 {
    LINE_JOURNEY_NUMBER_RANKING = 'LINE_JOURNEY_NUMBER_RANKING'
}

export enum TypeEnum39 {
    LINE_PROBLEM_STATIONS = 'LINE_PROBLEM_STATIONS'
}

export enum TypeEnum40 {
    LINE_ROUTE_VARIANTS = 'LINE_ROUTE_VARIANTS'
}

export enum TypeEnum41 {
    LINE_STATION_PERFORMANCE = 'LINE_STATION_PERFORMANCE'
}

export enum TypeEnum42 {
    LINE_SUMMARY = 'LINE_SUMMARY'
}

export enum TypeEnum43 {
    LINE_TIME_SERIES = 'LINE_TIME_SERIES'
}

export enum TypeEnum44 {
    NETWORK_EVENT_TIME_SERIES = 'NETWORK_EVENT_TIME_SERIES'
}

export enum TypeEnum45 {
    NETWORK_JOURNEY_TIME_SERIES = 'NETWORK_JOURNEY_TIME_SERIES'
}

export enum TypeEnum46 {
    NETWORK_LINE_RANKING = 'NETWORK_LINE_RANKING'
}

export enum TypeEnum47 {
    NETWORK_MAP_HOTSPOTS = 'NETWORK_MAP_HOTSPOTS'
}

export enum TypeEnum48 {
    NETWORK_STATION_RANKING = 'NETWORK_STATION_RANKING'
}

export enum TypeEnum49 {
    STATION_BENCHMARK = 'STATION_BENCHMARK'
}

export enum TypeEnum50 {
    STATION_DIRECTIONS = 'STATION_DIRECTIONS'
}

export enum TypeEnum51 {
    STATION_EVENT_DETAILS = 'STATION_EVENT_DETAILS'
}

export enum TypeEnum52 {
    STATION_LINE_RANKING = 'STATION_LINE_RANKING'
}

export enum TypeEnum53 {
    STATION_TIME_SERIES = 'STATION_TIME_SERIES'
}

export type GetApiV1JourneyData = {
    body?: never;
    path?: never;
    query?: {
        journeyId?: string;
    };
    url: '/api/v1/journey';
};

export type GetApiV1JourneyErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
    /**
     * Bad Gateway
     */
    502: unknown;
};

export type GetApiV1JourneyError = GetApiV1JourneyErrors[keyof GetApiV1JourneyErrors];

export type GetApiV1JourneyResponses = {
    /**
     * OK
     */
    200: Journey;
};

export type GetApiV1JourneyResponse = GetApiV1JourneyResponses[keyof GetApiV1JourneyResponses];

export type PostApiV1JourneyBatchData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/v1/journey/batch';
};

export type PostApiV1JourneyBatchErrors = {
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
    /**
     * Bad Gateway
     */
    502: unknown;
};

export type PostApiV1JourneyBatchError = PostApiV1JourneyBatchErrors[keyof PostApiV1JourneyBatchErrors];

export type PostApiV1JourneyBatchResponses = {
    /**
     * OK
     */
    200: Array<Journey>;
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1JourneyBatchResponse = PostApiV1JourneyBatchResponses[keyof PostApiV1JourneyBatchResponses];

export type PostApiV1StationsSearchData = {
    body: StationBySerchtermRequest;
    path?: never;
    query?: never;
    url: '/api/v1/stations/search';
};

export type PostApiV1StationsSearchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
    /**
     * Bad Gateway
     */
    502: unknown;
};

export type PostApiV1StationsSearchError = PostApiV1StationsSearchErrors[keyof PostApiV1StationsSearchErrors];

export type PostApiV1StationsSearchResponses = {
    /**
     * OK
     */
    200: Array<Station>;
};

export type PostApiV1StationsSearchResponse = PostApiV1StationsSearchResponses[keyof PostApiV1StationsSearchResponses];

export type PostApiV1StationsNearbyData = {
    body: StationByGeographicCoordinatesRequest;
    path?: never;
    query?: never;
    url: '/api/v1/stations/nearby';
};

export type PostApiV1StationsNearbyErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
    /**
     * Bad Gateway
     */
    502: unknown;
};

export type PostApiV1StationsNearbyError = PostApiV1StationsNearbyErrors[keyof PostApiV1StationsNearbyErrors];

export type PostApiV1StationsNearbyResponses = {
    /**
     * OK
     */
    200: Array<BaseStation>;
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1StationsNearbyResponse = PostApiV1StationsNearbyResponses[keyof PostApiV1StationsNearbyResponses];

export type GetApiV1StationsByEvaNumberData = {
    body?: never;
    path: {
        evaNumber: number;
    };
    query?: never;
    url: '/api/v1/stations/{evaNumber}';
};

export type GetApiV1StationsByEvaNumberErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1StationsByEvaNumberError = GetApiV1StationsByEvaNumberErrors[keyof GetApiV1StationsByEvaNumberErrors];

export type GetApiV1StationsByEvaNumberResponses = {
    /**
     * OK
     */
    200: Station;
};

export type GetApiV1StationsByEvaNumberResponse = GetApiV1StationsByEvaNumberResponses[keyof GetApiV1StationsByEvaNumberResponses];

export type GetApiV1StationsByEvaNumberGatheringData = {
    body?: never;
    path: {
        evaNumber: number;
    };
    query?: never;
    url: '/api/v1/stations/{evaNumber}/gathering';
};

export type GetApiV1StationsByEvaNumberGatheringErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1StationsByEvaNumberGatheringError = GetApiV1StationsByEvaNumberGatheringErrors[keyof GetApiV1StationsByEvaNumberGatheringErrors];

export type GetApiV1StationsByEvaNumberGatheringResponses = {
    /**
     * OK
     */
    200: StationGatheringInfo;
};

export type GetApiV1StationsByEvaNumberGatheringResponse = GetApiV1StationsByEvaNumberGatheringResponses[keyof GetApiV1StationsByEvaNumberGatheringResponses];

export type PostApiV1StationsBatchData = {
    body: Array<number | string>;
    path?: never;
    query?: never;
    url: '/api/v1/stations/batch';
};

export type PostApiV1StationsBatchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiV1StationsBatchError = PostApiV1StationsBatchErrors[keyof PostApiV1StationsBatchErrors];

export type PostApiV1StationsBatchResponses = {
    /**
     * OK
     */
    200: BaseStation;
};

export type PostApiV1StationsBatchResponse = PostApiV1StationsBatchResponses[keyof PostApiV1StationsBatchResponses];

export type PostApiV1StatisticsNetworkData = {
    body: NetworkStatisticsMetricRequest;
    path?: never;
    query?: never;
    url: '/api/v1/statistics/network';
};

export type PostApiV1StatisticsNetworkErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiV1StatisticsNetworkError = PostApiV1StatisticsNetworkErrors[keyof PostApiV1StatisticsNetworkErrors];

export type PostApiV1StatisticsNetworkResponses = {
    /**
     * OK
     */
    200: StatisticsMetricResponse;
};

export type PostApiV1StatisticsNetworkResponse = PostApiV1StatisticsNetworkResponses[keyof PostApiV1StatisticsNetworkResponses];

export type PostApiV1StatisticsNetworkMapHotspotsGeojsonData = {
    body: NetworkMapHotspotsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/statistics/network/map-hotspots.geojson';
};

export type PostApiV1StatisticsNetworkMapHotspotsGeojsonErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiV1StatisticsNetworkMapHotspotsGeojsonError = PostApiV1StatisticsNetworkMapHotspotsGeojsonErrors[keyof PostApiV1StatisticsNetworkMapHotspotsGeojsonErrors];

export type PostApiV1StatisticsNetworkMapHotspotsGeojsonResponses = {
    /**
     * OK
     */
    200: GeoJsonFeatureCollection;
};

export type PostApiV1StatisticsNetworkMapHotspotsGeojsonResponse = PostApiV1StatisticsNetworkMapHotspotsGeojsonResponses[keyof PostApiV1StatisticsNetworkMapHotspotsGeojsonResponses];

export type PostApiV1StatisticsStationsData = {
    body: StationStatisticsMetricRequest;
    path?: never;
    query?: never;
    url: '/api/v1/statistics/stations';
};

export type PostApiV1StatisticsStationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiV1StatisticsStationsError = PostApiV1StatisticsStationsErrors[keyof PostApiV1StatisticsStationsErrors];

export type PostApiV1StatisticsStationsResponses = {
    /**
     * OK
     */
    200: StatisticsMetricResponse;
};

export type PostApiV1StatisticsStationsResponse = PostApiV1StatisticsStationsResponses[keyof PostApiV1StatisticsStationsResponses];

export type PostApiV1StatisticsLinesData = {
    body: LineStatisticsMetricRequest;
    path?: never;
    query?: never;
    url: '/api/v1/statistics/lines';
};

export type PostApiV1StatisticsLinesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiV1StatisticsLinesError = PostApiV1StatisticsLinesErrors[keyof PostApiV1StatisticsLinesErrors];

export type PostApiV1StatisticsLinesResponses = {
    /**
     * OK
     */
    200: StatisticsMetricResponse;
};

export type PostApiV1StatisticsLinesResponse = PostApiV1StatisticsLinesResponses[keyof PostApiV1StatisticsLinesResponses];

export type PostApiV1StatisticsJourneysData = {
    body: JourneyStatisticsMetricRequest;
    path?: never;
    query?: never;
    url: '/api/v1/statistics/journeys';
};

export type PostApiV1StatisticsJourneysErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiV1StatisticsJourneysError = PostApiV1StatisticsJourneysErrors[keyof PostApiV1StatisticsJourneysErrors];

export type PostApiV1StatisticsJourneysResponses = {
    /**
     * OK
     */
    200: StatisticsMetricResponse;
};

export type PostApiV1StatisticsJourneysResponse = PostApiV1StatisticsJourneysResponses[keyof PostApiV1StatisticsJourneysResponses];

export type PostApiV1TimetableDeparturesData = {
    body: TimetableRequest;
    path?: never;
    query?: never;
    url: '/api/v1/timetable/departures';
};

export type PostApiV1TimetableDeparturesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
    /**
     * Bad Gateway
     */
    502: unknown;
};

export type PostApiV1TimetableDeparturesError = PostApiV1TimetableDeparturesErrors[keyof PostApiV1TimetableDeparturesErrors];

export type PostApiV1TimetableDeparturesResponses = {
    /**
     * OK
     */
    200: Array<TimetableDeparture>;
};

export type PostApiV1TimetableDeparturesResponse = PostApiV1TimetableDeparturesResponses[keyof PostApiV1TimetableDeparturesResponses];

export type PostApiV1TimetableArrivalsData = {
    body: TimetableRequest;
    path?: never;
    query?: never;
    url: '/api/v1/timetable/arrivals';
};

export type PostApiV1TimetableArrivalsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
    /**
     * Bad Gateway
     */
    502: unknown;
};

export type PostApiV1TimetableArrivalsError = PostApiV1TimetableArrivalsErrors[keyof PostApiV1TimetableArrivalsErrors];

export type PostApiV1TimetableArrivalsResponses = {
    /**
     * OK
     */
    200: Array<TimetableArrival>;
};

export type PostApiV1TimetableArrivalsResponse = PostApiV1TimetableArrivalsResponses[keyof PostApiV1TimetableArrivalsResponses];
