// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: "https://navigator.voldechse.wtf/" | (string & {});
};

export type BaseStation = {
	evaNumber: number | string;
	name: string;
	position: StationPosition;
};

/**
 * Represents a request to estimate the size of data within a specified time range.
 */
export type EstimateSizeRequest = {
	/**
	 * The start time of the range for which to estimate size.
	 */
	start: string;
	/**
	 * The start time of the range for which to estimate size.
	 */
	end: string;
};

export enum InformationType {
	JOURNEY_ATTRIBUTE = "JOURNEY_ATTRIBUTE",
	DISRUPTION = "DISRUPTION",
	MESSAGE = "MESSAGE",
	RIS_QUALITY_DEVIATION = "RIS_QUALITY_DEVIATION",
	RIS_CAUSE_REASON = "RIS_CAUSE_REASON"
}

export enum JourneyType {
	REGULAR = "REGULAR",
	REPLACEMENT = "REPLACEMENT",
	RELIEF = "RELIEF",
	EXTRA = "EXTRA"
}

export type MeasuredStatisticValue = {
	date: string;
	value: number | string;
};

export type MeasuredTimerangeStatistic = {
	unit: StatisticUnit;
	timerange: Timerange;
	values: Array<MeasuredStatisticValue>;
	startedWith: number | string;
	changedBy: number | string;
	total: number | string;
};

export type ProblemDetails = {
	type?: null | string;
	title?: null | string;
	status?: null | number | string;
	detail?: null | string;
	instance?: null | string;
};

export type Station = {
	transports: Array<TransportType>;
	ril100?: null | Array<string>;
	evaNumber: number | string;
	name: string;
	position: StationPosition;
};

/**
 * Represents a request to find stations near specific geographic coordinates.
 */
export type StationByGeographicCoordinatesRequest = {
	/**
	 * The latitude of the location.
	 */
	latitude: number | string;
	/**
	 * The longitude of the location.
	 */
	longitude: number | string;
	/**
	 * The maximum number of stations to return. Defaults to 100.
	 */
	limit?: null | number | string;
	/**
	 * The maximum distance in meters to search for stations. Defaults to 1000.
	 */
	maxDistance?: null | number | string;
};

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location
 * types.
 */
export type StationBySerchtermRequest = {
	/**
	 * The term to search for in station names or codes.
	 */
	searchTerm: string;
	/**
	 * The maximum number of results to return. Defaults to 10 if not specified.
	 */
	maxResults?: null | number | string;
	/**
	 * An array of location types to filter the search results. Defaults to ['ALL'] if not specified.
	 */
	locationTypes?: null | Array<string>;
};

export type StationGatheringInfo = {
	queryingEnabled: boolean;
	lastQueried?: null | string;
	active: Array<TransportType>;
	disabled: Array<TransportType>;
};

export type StationPosition = {
	latitude: number | string;
	longitude: number | string;
};

export enum StatisticUnit {
	BYTES = "BYTES"
}

export type Timerange = {
	start: string;
	end: string;
};

export type TimetableArrival = {
	journeyId: string;
	administration: TimetableEntryAdministration;
	transport: TimetableEntryTransport;
	origin: TimetableEntryRichStopPlace;
	differingOrigin?: null | TimetableEntryRichStopPlace;
	direction: Array<TimetableEntryStopPlace>;
	viaStops: Array<TimetableEntryRichStopPlace>;
	schedule: TimetableEntrySchedule;
	informations: Array<TimetableEntryInformation>;
	cancelled: boolean;
	additional?: null | boolean;
	demand?: null | boolean;
	travelsWith?: null | Array<string>;
};

export type TimetableDeparture = {
	journeyId: string;
	administration: TimetableEntryAdministration;
	transport: TimetableEntryTransport;
	destination: TimetableEntryRichStopPlace;
	differingDestination?: null | TimetableEntryRichStopPlace;
	direction: Array<TimetableEntryStopPlace>;
	viaStops: Array<TimetableEntryRichStopPlace>;
	schedule: TimetableEntrySchedule;
	informations: Array<TimetableEntryInformation>;
	cancelled: boolean;
	additional?: null | boolean;
	demand?: null | boolean;
	travelsWith?: null | Array<TimetableEntryCoupledTransport>;
};

export type TimetableEntryAdministration = {
	administrationId: string;
	operatorCode: string;
	operatorName: string;
};

export type TimetableEntryCoupledTransport = {
	journeyId: string;
	separationAt: TimetableEntryStopPlace;
};

export type TimetableEntryInformation = {
	type: InformationType;
	text: string;
	textShort?: null | string;
};

export type TimetableEntryRichStopPlace = {
	cancelled: boolean;
	additional?: null | boolean;
	name: string;
	evaNumber: number | string;
};

export type TimetableEntrySchedule = {
	plannedTime: string;
	actualTime: string;
	delay?: number | string;
	plannedPlatform?: null | string;
	actualPlatform?: null | string;
};

export type TimetableEntryStopPlace = {
	name: string;
	evaNumber: number | string;
};

export type TimetableEntryTransport = {
	type: TransportType;
	replacementType?: null | TransportType;
	category?: null | string;
	categoryInternal?: null | string;
	journeyType: JourneyType;
	journeyDescription: string;
	number: number | string;
	line?: null | string;
};

/**
 * Represents a request to retrieve a timetable for a specific station, including the station's EVA number, the desired
 * date and time, and the duration for which to retrieve timetable data.
 */
export type TimetableRequest = {
	/**
	 * The evaNumber to lookup a timetable for
	 */
	evaNumber: number | string;
	/**
	 * The date and time for which to retrieve the timetable. Defaults to the current date and time if not specified.
	 */
	when?: null | string;
	/**
	 * The duration in minutes for which to retrieve the timetable. Defaults to 60 minutes if not specified.
	 */
	duration?: null | number | string;
};

export enum TransportType {
	UNKNOWN = "UNKNOWN",
	HIGH_SPEED_TRAIN = "HIGH_SPEED_TRAIN",
	INTERCITY_TRAIN = "INTERCITY_TRAIN",
	INTER_REGIONAL_TRAIN = "INTER_REGIONAL_TRAIN",
	REGIONAL_TRAIN = "REGIONAL_TRAIN",
	CITY_TRAIN = "CITY_TRAIN",
	SUBWAY = "SUBWAY",
	TRAM = "TRAM",
	BUS = "BUS",
	FERRY = "FERRY",
	FLIGHT = "FLIGHT",
	CAR = "CAR",
	TAXI = "TAXI",
	SHUTTLE = "SHUTTLE",
	BIKE = "BIKE",
	SCOOTER = "SCOOTER",
	WALK = "WALK"
}

export type GetApiV1StationsData = {
	body?: never;
	path?: never;
	query?: {
		evaNumber?: number | string;
	};
	url: "/api/v1/stations";
};

export type GetApiV1StationsErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * Not Found
	 */
	404: ProblemDetails;
};

export type GetApiV1StationsError = GetApiV1StationsErrors[keyof GetApiV1StationsErrors];

export type GetApiV1StationsResponses = {
	/**
	 * OK
	 */
	200: Station;
};

export type GetApiV1StationsResponse = GetApiV1StationsResponses[keyof GetApiV1StationsResponses];

export type PostApiV1StationsData = {
	body: StationBySerchtermRequest;
	path?: never;
	query?: never;
	url: "/api/v1/stations";
};

export type PostApiV1StationsErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1StationsError = PostApiV1StationsErrors[keyof PostApiV1StationsErrors];

export type PostApiV1StationsResponses = {
	/**
	 * OK
	 */
	200: Array<Station>;
};

export type PostApiV1StationsResponse = PostApiV1StationsResponses[keyof PostApiV1StationsResponses];

export type PostApiV1StationsNearbyData = {
	body: StationByGeographicCoordinatesRequest;
	path?: never;
	query?: never;
	url: "/api/v1/stations/nearby";
};

export type PostApiV1StationsNearbyErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * Not Found
	 */
	404: ProblemDetails;
};

export type PostApiV1StationsNearbyError = PostApiV1StationsNearbyErrors[keyof PostApiV1StationsNearbyErrors];

export type PostApiV1StationsNearbyResponses = {
	/**
	 * OK
	 */
	200: Array<BaseStation>;
};

export type PostApiV1StationsNearbyResponse = PostApiV1StationsNearbyResponses[keyof PostApiV1StationsNearbyResponses];

export type GetApiV1StationsGatheringData = {
	body?: never;
	path?: never;
	query?: {
		evaNumber?: number | string;
	};
	url: "/api/v1/stations/gathering";
};

export type GetApiV1StationsGatheringErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * Not Found
	 */
	404: ProblemDetails;
};

export type GetApiV1StationsGatheringError = GetApiV1StationsGatheringErrors[keyof GetApiV1StationsGatheringErrors];

export type GetApiV1StationsGatheringResponses = {
	/**
	 * OK
	 */
	200: StationGatheringInfo;
};

export type GetApiV1StationsGatheringResponse = GetApiV1StationsGatheringResponses[keyof GetApiV1StationsGatheringResponses];

export type PostApiV1StatisticsEstimateSizeData = {
	body: EstimateSizeRequest;
	path?: never;
	query?: never;
	url: "/api/v1/statistics/estimate-size";
};

export type PostApiV1StatisticsEstimateSizeErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1StatisticsEstimateSizeError =
	PostApiV1StatisticsEstimateSizeErrors[keyof PostApiV1StatisticsEstimateSizeErrors];

export type PostApiV1StatisticsEstimateSizeResponses = {
	/**
	 * OK
	 */
	200: MeasuredTimerangeStatistic;
};

export type PostApiV1StatisticsEstimateSizeResponse =
	PostApiV1StatisticsEstimateSizeResponses[keyof PostApiV1StatisticsEstimateSizeResponses];

export type PostApiV1TimetableDeparturesData = {
	body: TimetableRequest;
	path?: never;
	query?: never;
	url: "/api/v1/timetable/departures";
};

export type PostApiV1TimetableDeparturesErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1TimetableDeparturesError = PostApiV1TimetableDeparturesErrors[keyof PostApiV1TimetableDeparturesErrors];

export type PostApiV1TimetableDeparturesResponses = {
	/**
	 * OK
	 */
	200: Array<TimetableDeparture>;
};

export type PostApiV1TimetableDeparturesResponse =
	PostApiV1TimetableDeparturesResponses[keyof PostApiV1TimetableDeparturesResponses];

export type PostApiV1TimetableArrivalsData = {
	body: TimetableRequest;
	path?: never;
	query?: never;
	url: "/api/v1/timetable/arrivals";
};

export type PostApiV1TimetableArrivalsErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
};

export type PostApiV1TimetableArrivalsError = PostApiV1TimetableArrivalsErrors[keyof PostApiV1TimetableArrivalsErrors];

export type PostApiV1TimetableArrivalsResponses = {
	/**
	 * OK
	 */
	200: Array<TimetableArrival>;
};

export type PostApiV1TimetableArrivalsResponse = PostApiV1TimetableArrivalsResponses[keyof PostApiV1TimetableArrivalsResponses];
