// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vEventMetrics = v.object({
    plannedEvents: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    cancelledEvents: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    servedEvents: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    cancellationRate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    operativePunctuality5Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    customerReliability5Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    operativePunctuality15Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    customerReliability15Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    averageDelaySeconds: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    delayDebtMinutes: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))]),
    late30Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    late60Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))]))
});

export const vEventHeatmapCell = v.object({
    weekday: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    hour: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    eventMetrics: vEventMetrics
});

export const vEventTimeSeriesPoint = v.object({
    bucketStart: v.pipe(v.string(), v.isoTimestamp()),
    eventMetrics: vEventMetrics
});

export const vGeoJsonPoint = v.object({
    type: v.string(),
    coordinates: v.array(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]))
});

export const vGeoJsonFeature = v.object({
    type: v.string(),
    id: v.string(),
    geometry: vGeoJsonPoint,
    properties: v.record(v.string(), v.unknown())
});

export const vGeoJsonFeatureCollection = v.object({
    type: v.string(),
    features: v.array(vGeoJsonFeature)
});

export const vJourneyAdministration = v.object({
    administrationId: v.string(),
    operatorCode: v.string(),
    operatorName: v.string()
});

export const vJourneyCalendarItem = v.object({
    serviceDate: v.pipe(v.string(), v.isoDate()),
    status: v.string(),
    destinationDelaySeconds: v.nullable(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    outcome: v.string()
});

export const vJourneyDailyOutcomeItem = v.object({
    serviceDate: v.pipe(v.string(), v.isoDate()),
    outcome: v.string(),
    destinationDelaySeconds: v.nullable(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationPunctualityClass: v.string(),
    fullyCancelled: v.boolean(),
    partiallyCancelled: v.boolean(),
    destinationNotReached: v.boolean()
});

export const vJourneyMetrics = v.object({
    plannedJourneys: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    completedJourneys: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    fullyCancelledJourneys: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    partiallyCancelledJourneys: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    destinationNotReachedJourneys: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    fullCancellationRate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    partialCancellationRate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    destinationNotReachedRate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    journeyCompletionRate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    destinationPunctuality5Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    destinationPunctuality15Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    averageDestinationDelaySeconds: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    destinationDelayDebtMinutes: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])
});

export const vJourneyHeatmapCell = v.object({
    weekday: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    hour: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    journeyMetrics: vJourneyMetrics
});

export const vJourneyRichStopPlace = v.object({
    cancelled: v.boolean(),
    name: v.string(),
    evaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])
});

export const vJourneyStopPlace = v.object({
    name: v.string(),
    evaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])
});

export const vJourneyTimeSeriesPoint = v.object({
    bucketStart: v.pipe(v.string(), v.isoTimestamp()),
    journeyMetrics: vJourneyMetrics
});

export const vJourneyType = v.picklist([
    'REGULAR',
    'REPLACEMENT',
    'RELIEF',
    'EXTRA'
]);

export const vLineTimeSeriesPoint = v.object({
    bucketStart: v.pipe(v.string(), v.isoTimestamp()),
    journeyMetrics: vJourneyMetrics,
    eventMetrics: vEventMetrics
});

export const vMessageKey = v.picklist([
    'UNPLANNED_INFO',
    'GENERAL_WARNING',
    'ADDITIONAL_COACHES',
    'MISSING_COACHES',
    'CHANGED_COACH_SEQUENCE',
    'REPLACEMENT_SERVICE',
    'ADDITIONAL_STOP',
    'WIFI_DISTRIBUTION',
    'NO_FIRST_CLASS',
    'ACCESSIBILITY_WARNING',
    'RESERVATIONS_MISSING',
    'RESERVATIONS_REQUIRED',
    'NO_FOOD',
    'BICYCLE_WARNING',
    'BICYCLE_TRANSPORT',
    'BICYCLE_TRANSPORT_NOT_POSSIBLE',
    'BICYCLE_RESERVATION_REQUIRED',
    'TICKET_INFORMATION'
]);

export const vMessageType = v.picklist([
    'ATTRIBUTE',
    'DISRUPTION',
    'NOTE',
    'RIS_CAUSE',
    'RIS_QUALITY_DEVIATION'
]);

export const vMetricPage = v.object({
    offset: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    limit: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    totalItems: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])
});

export const vProblemDetails = v.object({
    type: v.nullish(v.string()),
    title: v.nullish(v.string()),
    status: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    detail: v.nullish(v.string()),
    instance: v.nullish(v.string())
});

export const vScheduleType = v.picklist(['ARRIVAL', 'DEPARTURE']);

export const vArrivalDepartureComparisonItem = v.object({
    scheduleType: vScheduleType,
    eventMetrics: vEventMetrics
});

/**
 * Represents a request to find stations near specific geographic coordinates.
 */
export const vStationByGeographicCoordinatesRequest = v.object({
    latitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]),
    longitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]),
    limit: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]), 100),
    maxDistance: v.nullish(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]), 1000)
});

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location types.
 */
export const vStationBySerchtermRequest = v.object({
    searchTerm: v.string(),
    maxResults: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]), 10),
    locationTypes: v.nullish(v.array(v.string()), ['ALL'])
});

export const vStationPosition = v.object({
    latitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]),
    longitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))])
});

export const vBaseStation = v.object({
    evaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    name: v.string(),
    position: vStationPosition
});

export const vStationReference = v.object({
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    stationName: v.nullish(v.string()),
    latitude: v.nullish(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))])),
    longitude: v.nullish(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]))
});

export const vJourneyDelayBuildUpItem = v.object({
    station: vStationReference,
    medianDelaySeconds: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    p95DelaySeconds: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))]))
});

export const vJourneyStopProfileItem = v.object({
    station: vStationReference,
    plannedTime: v.pipe(v.string(), v.regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/)),
    scheduleType: vScheduleType,
    plannedEvents: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    cancelledEvents: v.union([v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')), v.pipe(v.union([
            v.number(),
            v.string(),
            v.bigint()
        ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))]),
    customerReliability5Rate: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    medianDelaySeconds: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    p95DelaySeconds: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))]))
});

export const vLineStationPerformanceItem = v.object({
    station: vStationReference,
    eventMetrics: vEventMetrics
});

export const vStationDirectionItem = v.object({
    directionType: v.string(),
    station: vStationReference,
    eventMetrics: vEventMetrics
});

export const vStationEventRankingItem = v.object({
    station: vStationReference,
    eventMetrics: vEventMetrics
});

export const vStatisticsBucket = v.picklist([
    'HOUR',
    'DAY',
    'WEEK',
    'MONTH'
]);

export const vStatisticsResponseMeta = v.object({
    scope: v.string(),
    metric: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate()),
    bucket: vStatisticsBucket,
    timezone: v.string(),
    filters: v.record(v.string(), v.unknown())
});

export const vTimetableEntryAdministration = v.object({
    administrationId: v.string(),
    operatorCode: v.string(),
    operatorName: v.string()
});

export const vTimetableEntryMessage = v.object({
    type: vMessageType,
    key: vMessageKey,
    text: v.string(),
    textShort: v.nullish(v.string())
});

export const vTimetableEntryRichStopPlace = v.object({
    cancelled: v.boolean(),
    additional: v.nullish(v.boolean()),
    name: v.string(),
    evaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])
});

export const vTimetableEntryStopPlace = v.object({
    name: v.string(),
    evaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])
});

export const vTimetableEntryCoupledTransport = v.object({
    journeyId: v.string(),
    separationAt: v.nullish(vTimetableEntryStopPlace)
});

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location types.
 */
export const vTimetableRequest = v.object({
    evaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    when: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    duration: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]), 60)
});

export const vTimeType = v.picklist([
    'SCHEDULE',
    'PREVIEW',
    'REAL'
]);

export const vJourneyScheduledEvent = v.object({
    stopPlace: vJourneyStopPlace,
    differingStopPlace: vJourneyStopPlace,
    cancelled: v.boolean(),
    additional: v.boolean(),
    noPassengerChange: v.boolean(),
    demand: v.boolean(),
    scheduleType: vScheduleType,
    plannedTime: v.pipe(v.string(), v.isoTimestamp()),
    actualTime: v.pipe(v.string(), v.isoTimestamp()),
    delay: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    plannedPlatform: v.nullish(v.string()),
    actualPlatform: v.nullish(v.string()),
    timeType: vTimeType,
    travelsWith: v.nullish(v.array(v.string())),
    messageIds: v.nullish(v.array(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])))
});

export const vTimetableEntrySchedule = v.object({
    plannedTime: v.pipe(v.string(), v.isoTimestamp()),
    actualTime: v.pipe(v.string(), v.isoTimestamp()),
    delay: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    plannedPlatform: v.nullish(v.string()),
    actualPlatform: v.nullish(v.string()),
    timeType: vTimeType
});

export const vTransportType = v.picklist([
    'UNKNOWN',
    'HIGH_SPEED_TRAIN',
    'INTERCITY_TRAIN',
    'INTER_REGIONAL_TRAIN',
    'REGIONAL_TRAIN',
    'CITY_TRAIN',
    'SUBWAY',
    'TRAM',
    'BUS',
    'FERRY',
    'FLIGHT',
    'CAR',
    'TAXI',
    'SHUTTLE',
    'BIKE',
    'SCOOTER',
    'WALK'
]);

export const vJourneyTransport = v.object({
    type: vTransportType,
    replacementType: v.nullish(vTransportType),
    category: v.nullish(v.string()),
    categoryInternal: v.nullish(v.string()),
    journeyDescription: v.string(),
    label: v.nullish(v.string()),
    line: v.nullish(v.string()),
    number: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])
});

export const vLineHourMatrixItem = v.object({
    lineName: v.string(),
    transportType: vTransportType,
    hour: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    eventMetrics: vEventMetrics
});

export const vLineReference = v.object({
    lineName: v.string(),
    journeyNumber: v.nullable(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    transportType: vTransportType,
    origin: v.nullable(vStationReference),
    destination: v.nullable(vStationReference)
});

export const vJourneyNumberRankingItem = v.object({
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    line: vLineReference,
    journeyMetrics: vJourneyMetrics
});

export const vLineJourneyRankingItem = v.object({
    line: vLineReference,
    journeyMetrics: vJourneyMetrics
});

export const vNetworkMapHotspotsRequest = v.object({
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    includeReplacement: v.optional(v.boolean()),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vRouteVariantItem = v.object({
    variantKey: v.string(),
    origin: vStationReference,
    destination: vStationReference,
    transportType: vTransportType,
    journeyMetrics: vJourneyMetrics
});

export const vStation = v.object({
    transports: v.array(vTransportType),
    ril100: v.nullish(v.array(v.string())),
    evaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    name: v.string(),
    position: vStationPosition
});

export const vStationEventDetailItem = v.object({
    stopPlaceId: v.pipe(v.string(), v.uuid()),
    journeyId: v.string(),
    journeyDate: v.pipe(v.string(), v.isoDate()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    plannedTime: v.pipe(v.string(), v.isoTimestamp()),
    scheduleType: vScheduleType,
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.string(),
    originEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    journeyStartTime: v.pipe(v.string(), v.isoTimestamp()),
    destinationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    journeyEndTime: v.pipe(v.string(), v.isoTimestamp()),
    stopCancelled: v.boolean(),
    transportType: vTransportType,
    eventDelaySeconds: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    isReplacement: v.boolean()
});

export const vStationGatheringInfo = v.object({
    queryingEnabled: v.boolean(),
    lastQueried: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
    active: v.array(vTransportType),
    disabled: v.array(vTransportType)
});

export const vStationLineRankingItem = v.object({
    line: vLineReference,
    eventMetrics: vEventMetrics
});

export const vTimetableEntryTransport = v.object({
    type: vTransportType,
    replacementType: v.nullish(vTransportType),
    category: v.nullish(v.string()),
    categoryInternal: v.nullish(v.string()),
    journeyType: vJourneyType,
    journeyDescription: v.string(),
    number: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    line: v.nullish(v.string())
});

export const vTimetableArrival = v.object({
    journeyId: v.pipe(v.string(), v.maxLength(82)),
    administration: vTimetableEntryAdministration,
    transport: vTimetableEntryTransport,
    origin: vTimetableEntryRichStopPlace,
    differingOrigin: v.nullish(vTimetableEntryRichStopPlace),
    direction: v.array(vTimetableEntryStopPlace),
    viaStops: v.array(vTimetableEntryRichStopPlace),
    schedule: vTimetableEntrySchedule,
    messages: v.array(vTimetableEntryMessage),
    cancelled: v.boolean(),
    additional: v.nullish(v.boolean()),
    demand: v.nullish(v.boolean()),
    travelsWith: v.nullish(v.array(v.string()))
});

export const vTimetableDeparture = v.object({
    journeyId: v.pipe(v.string(), v.maxLength(82)),
    administration: vTimetableEntryAdministration,
    transport: vTimetableEntryTransport,
    destination: vTimetableEntryRichStopPlace,
    differingDestination: v.nullish(vTimetableEntryRichStopPlace),
    direction: v.array(vTimetableEntryStopPlace),
    viaStops: v.array(vTimetableEntryRichStopPlace),
    schedule: vTimetableEntrySchedule,
    messages: v.array(vTimetableEntryMessage),
    cancelled: v.boolean(),
    additional: v.nullish(v.boolean()),
    demand: v.nullish(v.boolean()),
    travelsWith: v.nullish(v.array(vTimetableEntryCoupledTransport))
});

export const vTransportTypeComparisonItem = v.object({
    transportType: vTransportType,
    eventMetrics: vEventMetrics,
    journeyMetrics: vJourneyMetrics
});

export const vTransportTypeMixItem = v.object({
    transportType: vTransportType,
    share: v.nullable(v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])),
    eventMetrics: vEventMetrics
});

export const vTypeEnum = v.picklist(['ATTRIBUTE']);

export const vJourneyMessageAttributeMessage = v.object({
    type: v.optional(vTypeEnum),
    messageId: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    key: vMessageKey,
    text: v.string()
});

export const vTypeEnum2 = v.picklist(['DISRUPTION']);

export const vJourneyMessageDisruptionMessage = v.object({
    type: v.optional(vTypeEnum2),
    cause: v.nullish(v.string()),
    effect: v.nullish(v.string()),
    disruptionId: v.nullish(v.string()),
    textShort: v.nullish(v.string()),
    messageId: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    key: vMessageKey,
    text: v.string()
});

export const vTypeEnum3 = v.picklist(['NOTE']);

export const vJourneyMessageNoteMessage = v.object({
    type: v.optional(vTypeEnum3),
    category: v.nullish(v.string()),
    textShort: v.nullish(v.string()),
    messageId: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    key: vMessageKey,
    text: v.string()
});

export const vTypeEnum4 = v.picklist(['RIS_CAUSE']);

export const vJourneyMessageRisCauseMessage = v.object({
    type: v.optional(vTypeEnum4),
    messageId: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    key: vMessageKey,
    text: v.string()
});

export const vTypeEnum5 = v.picklist(['RIS_QUALITY_DEVIATION']);

export const vJourneyMessageRisQualityDeviationMessage = v.object({
    type: v.optional(vTypeEnum5),
    messageId: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    key: vMessageKey,
    text: v.string()
});

export const vJourneyMessage = v.union([
    v.intersect([v.object({
            type: v.optional(v.literal('ATTRIBUTE'))
        }), vJourneyMessageAttributeMessage]),
    v.intersect([v.object({
            type: v.optional(v.literal('DISRUPTION'))
        }), vJourneyMessageDisruptionMessage]),
    v.intersect([v.object({
            type: v.optional(v.literal('NOTE'))
        }), vJourneyMessageNoteMessage]),
    v.intersect([v.object({
            type: v.optional(v.literal('RIS_CAUSE'))
        }), vJourneyMessageRisCauseMessage]),
    v.intersect([v.object({
            type: v.optional(v.literal('RIS_QUALITY_DEVIATION'))
        }), vJourneyMessageRisQualityDeviationMessage])
]);

export const vJourney = v.object({
    journeyId: v.pipe(v.string(), v.maxLength(82)),
    administration: vJourneyAdministration,
    type: vJourneyType,
    transport: vJourneyTransport,
    continuationBy: v.nullish(v.array(v.string())),
    continuationFor: v.nullish(v.array(v.string())),
    cancelled: v.boolean(),
    destination: vJourneyRichStopPlace,
    differingDestination: v.nullish(vJourneyStopPlace),
    origin: vJourneyRichStopPlace,
    differingOrigin: v.nullish(vJourneyStopPlace),
    scheduledEvents: v.array(vJourneyScheduledEvent),
    messages: v.array(vJourneyMessage)
});

export const vTypeEnum6 = v.picklist(['CALENDAR']);

export const vJourneyStatisticsMetricRequestJourneyCalendarRequest = v.object({
    type: v.optional(vTypeEnum6),
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.nullish(v.string()),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum7 = v.picklist(['DAILY_OUTCOMES']);

export const vJourneyStatisticsMetricRequestJourneyDailyOutcomesRequest = v.object({
    type: v.optional(vTypeEnum7),
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.nullish(v.string()),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum8 = v.picklist(['DELAY_BUILD_UP']);

export const vJourneyStatisticsMetricRequestJourneyDelayBuildUpRequest = v.object({
    type: v.optional(vTypeEnum8),
    scheduleType: v.nullish(vScheduleType),
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.nullish(v.string()),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum9 = v.picklist(['JOURNEY_KPIS']);

export const vJourneyStatisticsMetricRequestJourneyKpisRequest = v.object({
    type: v.optional(vTypeEnum9),
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.nullish(v.string()),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vLineStatisticsMetricRequestLineJourneyKpisRequest = v.object({
    type: v.optional(vTypeEnum9),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vNetworkStatisticsMetricRequestNetworkJourneyKpisRequest = v.object({
    type: v.optional(vTypeEnum9),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStatisticsMetricResultJourneyKpisResult = v.object({
    type: v.optional(vTypeEnum9),
    metrics: vJourneyMetrics
});

export const vTypeEnum10 = v.picklist(['PATTERN']);

export const vJourneyStatisticsMetricRequestJourneyPatternRequest = v.object({
    type: v.optional(vTypeEnum10),
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.nullish(v.string()),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum11 = v.picklist(['STOP_PROFILE']);

export const vJourneyStatisticsMetricRequestJourneyStopProfileRequest = v.object({
    type: v.optional(vTypeEnum11),
    scheduleType: v.nullish(vScheduleType),
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.nullish(v.string()),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vJourneyStatisticsMetricRequest = v.union([
    v.intersect([v.object({
            type: v.optional(v.literal('PATTERN'))
        }), vJourneyStatisticsMetricRequestJourneyPatternRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_KPIS'))
        }), vJourneyStatisticsMetricRequestJourneyKpisRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('DAILY_OUTCOMES'))
        }), vJourneyStatisticsMetricRequestJourneyDailyOutcomesRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('STOP_PROFILE'))
        }), vJourneyStatisticsMetricRequestJourneyStopProfileRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('DELAY_BUILD_UP'))
        }), vJourneyStatisticsMetricRequestJourneyDelayBuildUpRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('CALENDAR'))
        }), vJourneyStatisticsMetricRequestJourneyCalendarRequest])
]);

export const vTypeEnum12 = v.picklist(['EVENT_KPIS']);

export const vLineStatisticsMetricRequestLineEventKpisRequest = v.object({
    type: v.optional(vTypeEnum12),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vNetworkStatisticsMetricRequestNetworkEventKpisRequest = v.object({
    type: v.optional(vTypeEnum12),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStationStatisticsMetricRequestStationEventKpisRequest = v.object({
    type: v.optional(vTypeEnum12),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStatisticsMetricResultEventKpisResult = v.object({
    type: v.optional(vTypeEnum12),
    metrics: vEventMetrics
});

export const vTypeEnum13 = v.picklist(['JOURNEY_NUMBER_RANKING']);

export const vLineStatisticsMetricRequestLineJourneyNumberRankingRequest = v.object({
    type: v.optional(vTypeEnum13),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    limit: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(500)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    offset: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum14 = v.picklist(['PROBLEM_STATIONS']);

export const vLineStatisticsMetricRequestLineProblemStationsRequest = v.object({
    type: v.optional(vTypeEnum14),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    limit: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(500)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    offset: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum15 = v.picklist(['ROUTE_VARIANTS']);

export const vLineStatisticsMetricRequestLineRouteVariantsRequest = v.object({
    type: v.optional(vTypeEnum15),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum16 = v.picklist(['STATION_PERFORMANCE']);

export const vLineStatisticsMetricRequestLineStationPerformanceRequest = v.object({
    type: v.optional(vTypeEnum16),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    limit: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(500)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    offset: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum17 = v.picklist(['SUMMARY']);

export const vLineStatisticsMetricRequestLineSummaryRequest = v.object({
    type: v.optional(vTypeEnum17),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum18 = v.picklist(['TIME_SERIES']);

export const vLineStatisticsMetricRequestLineTimeSeriesRequest = v.object({
    type: v.optional(vTypeEnum18),
    bucket: v.optional(vStatisticsBucket),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStationStatisticsMetricRequestStationTimeSeriesRequest = v.object({
    type: v.optional(vTypeEnum18),
    bucket: v.optional(vStatisticsBucket),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum19 = v.picklist(['WEEKDAY_HOUR_HEATMAP']);

export const vLineStatisticsMetricRequestLineWeekdayHourHeatmapRequest = v.object({
    type: v.optional(vTypeEnum19),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    lineName: v.string(),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vLineStatisticsMetricRequest = v.union([
    v.intersect([v.object({
            type: v.optional(v.literal('SUMMARY'))
        }), vLineStatisticsMetricRequestLineSummaryRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_KPIS'))
        }), vLineStatisticsMetricRequestLineJourneyKpisRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('EVENT_KPIS'))
        }), vLineStatisticsMetricRequestLineEventKpisRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('TIME_SERIES'))
        }), vLineStatisticsMetricRequestLineTimeSeriesRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('ROUTE_VARIANTS'))
        }), vLineStatisticsMetricRequestLineRouteVariantsRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('STATION_PERFORMANCE'))
        }), vLineStatisticsMetricRequestLineStationPerformanceRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_NUMBER_RANKING'))
        }), vLineStatisticsMetricRequestLineJourneyNumberRankingRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('WEEKDAY_HOUR_HEATMAP'))
        }), vLineStatisticsMetricRequestLineWeekdayHourHeatmapRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('PROBLEM_STATIONS'))
        }), vLineStatisticsMetricRequestLineProblemStationsRequest])
]);

export const vNetworkStatisticsMetricRequestNetworkWeekdayHourHeatmapRequest = v.object({
    type: v.optional(vTypeEnum19),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStationStatisticsMetricRequestStationWeekdayHourHeatmapRequest = v.object({
    type: v.optional(vTypeEnum19),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum20 = v.picklist(['EVENT_TIME_SERIES']);

export const vNetworkStatisticsMetricRequestNetworkEventTimeSeriesRequest = v.object({
    type: v.optional(vTypeEnum20),
    bucket: v.optional(vStatisticsBucket),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum21 = v.picklist(['JOURNEY_TIME_SERIES']);

export const vNetworkStatisticsMetricRequestNetworkJourneyTimeSeriesRequest = v.object({
    type: v.optional(vTypeEnum21),
    bucket: v.optional(vStatisticsBucket),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum22 = v.picklist(['LINE_RANKING']);

export const vNetworkStatisticsMetricRequestNetworkLineRankingRequest = v.object({
    type: v.optional(vTypeEnum22),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    limit: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(500)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    offset: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStationStatisticsMetricRequestStationLineRankingRequest = v.object({
    type: v.optional(vTypeEnum22),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    directionEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    limit: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(500)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    offset: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum23 = v.picklist(['STATION_RANKING']);

export const vNetworkStatisticsMetricRequestNetworkStationRankingRequest = v.object({
    type: v.optional(vTypeEnum23),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    includeReplacement: v.optional(v.boolean()),
    minVolume: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    limit: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(500)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    offset: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum24 = v.picklist(['TRANSPORT_TYPE_COMPARISON']);

export const vNetworkStatisticsMetricRequestNetworkTransportTypeComparisonRequest = v.object({
    type: v.optional(vTypeEnum24),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vNetworkStatisticsMetricRequest = v.union([
    v.intersect([v.object({
            type: v.optional(v.literal('EVENT_KPIS'))
        }), vNetworkStatisticsMetricRequestNetworkEventKpisRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_KPIS'))
        }), vNetworkStatisticsMetricRequestNetworkJourneyKpisRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('EVENT_TIME_SERIES'))
        }), vNetworkStatisticsMetricRequestNetworkEventTimeSeriesRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_TIME_SERIES'))
        }), vNetworkStatisticsMetricRequestNetworkJourneyTimeSeriesRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('WEEKDAY_HOUR_HEATMAP'))
        }), vNetworkStatisticsMetricRequestNetworkWeekdayHourHeatmapRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('TRANSPORT_TYPE_COMPARISON'))
        }), vNetworkStatisticsMetricRequestNetworkTransportTypeComparisonRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('STATION_RANKING'))
        }), vNetworkStatisticsMetricRequestNetworkStationRankingRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_RANKING'))
        }), vNetworkStatisticsMetricRequestNetworkLineRankingRequest])
]);

export const vStatisticsMetricResultTransportTypeComparisonResult = v.object({
    type: v.optional(vTypeEnum24),
    items: v.array(vTransportTypeComparisonItem)
});

export const vTypeEnum25 = v.picklist(['ARRIVAL_DEPARTURE_COMPARISON']);

export const vStationStatisticsMetricRequestStationArrivalDepartureComparisonRequest = v.object({
    type: v.optional(vTypeEnum25),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStatisticsMetricResultArrivalDepartureComparisonResult = v.object({
    type: v.optional(vTypeEnum25),
    items: v.array(vArrivalDepartureComparisonItem)
});

export const vTypeEnum26 = v.picklist(['BENCHMARK']);

export const vStationStatisticsMetricRequestStationBenchmarkRequest = v.object({
    type: v.optional(vTypeEnum26),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum27 = v.picklist(['DIRECTIONS']);

export const vStationStatisticsMetricRequestStationDirectionsRequest = v.object({
    type: v.optional(vTypeEnum27),
    directionEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum28 = v.picklist(['EVENT_DETAILS']);

export const vStationStatisticsMetricRequestStationEventDetailsRequest = v.object({
    type: v.optional(vTypeEnum28),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    journeyNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    includeReplacement: v.optional(v.boolean()),
    limit: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(500)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    offset: v.optional(v.union([v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vTypeEnum29 = v.picklist(['LINE_HOUR_MATRIX']);

export const vStationStatisticsMetricRequestStationLineHourMatrixRequest = v.object({
    type: v.optional(vTypeEnum29),
    originEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    destinationEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    directionEvaNumber: v.nullish(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStatisticsMetricResultLineHourMatrixResult = v.object({
    type: v.optional(vTypeEnum29),
    items: v.array(vLineHourMatrixItem)
});

export const vTypeEnum30 = v.picklist(['TRANSPORT_TYPE_MIX']);

export const vStationStatisticsMetricRequestStationTransportTypeMixRequest = v.object({
    type: v.optional(vTypeEnum30),
    scheduleType: v.nullish(vScheduleType),
    transportTypes: v.optional(v.array(vTransportType)),
    administrationIds: v.optional(v.array(v.string())),
    includeReplacement: v.optional(v.boolean()),
    stationEvaNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(2147483647)), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    from: v.pipe(v.string(), v.isoDate()),
    to: v.pipe(v.string(), v.isoDate())
});

export const vStationStatisticsMetricRequest = v.union([
    v.intersect([v.object({
            type: v.optional(v.literal('EVENT_KPIS'))
        }), vStationStatisticsMetricRequestStationEventKpisRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('BENCHMARK'))
        }), vStationStatisticsMetricRequestStationBenchmarkRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('TIME_SERIES'))
        }), vStationStatisticsMetricRequestStationTimeSeriesRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('ARRIVAL_DEPARTURE_COMPARISON'))
        }), vStationStatisticsMetricRequestStationArrivalDepartureComparisonRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('WEEKDAY_HOUR_HEATMAP'))
        }), vStationStatisticsMetricRequestStationWeekdayHourHeatmapRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_RANKING'))
        }), vStationStatisticsMetricRequestStationLineRankingRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('DIRECTIONS'))
        }), vStationStatisticsMetricRequestStationDirectionsRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('TRANSPORT_TYPE_MIX'))
        }), vStationStatisticsMetricRequestStationTransportTypeMixRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_HOUR_MATRIX'))
        }), vStationStatisticsMetricRequestStationLineHourMatrixRequest]),
    v.intersect([v.object({
            type: v.optional(v.literal('EVENT_DETAILS'))
        }), vStationStatisticsMetricRequestStationEventDetailsRequest])
]);

export const vStatisticsMetricResultTransportTypeMixResult = v.object({
    type: v.optional(vTypeEnum30),
    items: v.array(vTransportTypeMixItem)
});

export const vTypeEnum31 = v.picklist(['EVENT_WEEKDAY_HOUR_HEATMAP']);

export const vStatisticsMetricResultEventWeekdayHourHeatmapResult = v.object({
    type: v.optional(vTypeEnum31),
    items: v.array(vEventHeatmapCell)
});

export const vTypeEnum32 = v.picklist(['JOURNEY_CALENDAR']);

export const vStatisticsMetricResultJourneyCalendarResult = v.object({
    type: v.optional(vTypeEnum32),
    items: v.array(vJourneyCalendarItem)
});

export const vTypeEnum33 = v.picklist(['JOURNEY_DAILY_OUTCOMES']);

export const vStatisticsMetricResultJourneyDailyOutcomesResult = v.object({
    type: v.optional(vTypeEnum33),
    items: v.array(vJourneyDailyOutcomeItem)
});

export const vTypeEnum34 = v.picklist(['JOURNEY_DELAY_BUILD_UP']);

export const vStatisticsMetricResultJourneyDelayBuildUpResult = v.object({
    type: v.optional(vTypeEnum34),
    items: v.array(vJourneyDelayBuildUpItem)
});

export const vTypeEnum35 = v.picklist(['JOURNEY_PATTERN']);

export const vStatisticsMetricResultJourneyPatternResult = v.object({
    type: v.optional(vTypeEnum35),
    journeyNumber: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    lineName: v.nullable(v.string()),
    transportType: v.nullable(vTransportType),
    scheduledStartTime: v.pipe(v.string(), v.regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/)),
    scheduledEndTime: v.pipe(v.string(), v.regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/)),
    mainOrigin: v.nullable(vStationReference),
    mainDestination: v.nullable(vStationReference),
    observedServiceDays: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    routeVariantCount: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])
});

export const vTypeEnum36 = v.picklist(['JOURNEY_STOP_PROFILE']);

export const vStatisticsMetricResultJourneyStopProfileResult = v.object({
    type: v.optional(vTypeEnum36),
    items: v.array(vJourneyStopProfileItem)
});

export const vTypeEnum37 = v.picklist(['JOURNEY_WEEKDAY_HOUR_HEATMAP']);

export const vStatisticsMetricResultJourneyWeekdayHourHeatmapResult = v.object({
    type: v.optional(vTypeEnum37),
    items: v.array(vJourneyHeatmapCell)
});

export const vTypeEnum38 = v.picklist(['LINE_JOURNEY_NUMBER_RANKING']);

export const vStatisticsMetricResultLineJourneyNumberRankingResult = v.object({
    type: v.optional(vTypeEnum38),
    items: v.array(vJourneyNumberRankingItem),
    page: vMetricPage
});

export const vTypeEnum39 = v.picklist(['LINE_PROBLEM_STATIONS']);

export const vStatisticsMetricResultLineProblemStationsResult = v.object({
    type: v.optional(vTypeEnum39),
    items: v.array(vLineStationPerformanceItem),
    page: vMetricPage
});

export const vTypeEnum40 = v.picklist(['LINE_ROUTE_VARIANTS']);

export const vStatisticsMetricResultLineRouteVariantsResult = v.object({
    type: v.optional(vTypeEnum40),
    items: v.array(vRouteVariantItem)
});

export const vTypeEnum41 = v.picklist(['LINE_STATION_PERFORMANCE']);

export const vStatisticsMetricResultLineStationPerformanceResult = v.object({
    type: v.optional(vTypeEnum41),
    items: v.array(vLineStationPerformanceItem),
    page: vMetricPage
});

export const vTypeEnum42 = v.picklist(['LINE_SUMMARY']);

export const vStatisticsMetricResultLineSummaryResult = v.object({
    type: v.optional(vTypeEnum42),
    lineName: v.string(),
    transportType: v.nullable(vTransportType),
    representativeJourneyNumbers: v.array(v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))])),
    routeVariantCount: v.union([v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))]),
    mainOrigin: v.nullable(vStationReference),
    mainDestination: v.nullable(vStationReference)
});

export const vTypeEnum43 = v.picklist(['LINE_TIME_SERIES']);

export const vStatisticsMetricResultLineTimeSeriesResult = v.object({
    type: v.optional(vTypeEnum43),
    items: v.array(vLineTimeSeriesPoint)
});

export const vTypeEnum44 = v.picklist(['NETWORK_EVENT_TIME_SERIES']);

export const vStatisticsMetricResultNetworkEventTimeSeriesResult = v.object({
    type: v.optional(vTypeEnum44),
    items: v.array(vEventTimeSeriesPoint)
});

export const vTypeEnum45 = v.picklist(['NETWORK_JOURNEY_TIME_SERIES']);

export const vStatisticsMetricResultNetworkJourneyTimeSeriesResult = v.object({
    type: v.optional(vTypeEnum45),
    items: v.array(vJourneyTimeSeriesPoint)
});

export const vTypeEnum46 = v.picklist(['NETWORK_LINE_RANKING']);

export const vStatisticsMetricResultNetworkLineRankingResult = v.object({
    type: v.optional(vTypeEnum46),
    items: v.array(vLineJourneyRankingItem),
    page: vMetricPage
});

export const vTypeEnum47 = v.picklist(['NETWORK_MAP_HOTSPOTS']);

export const vStatisticsMetricResultNetworkMapHotspotsResult = v.object({
    type: v.optional(vTypeEnum47),
    featureCollection: vGeoJsonFeatureCollection
});

export const vTypeEnum48 = v.picklist(['NETWORK_STATION_RANKING']);

export const vStatisticsMetricResultNetworkStationRankingResult = v.object({
    type: v.optional(vTypeEnum48),
    items: v.array(vStationEventRankingItem),
    page: vMetricPage
});

export const vTypeEnum49 = v.picklist(['STATION_BENCHMARK']);

export const vStatisticsMetricResultStationBenchmarkResult = v.object({
    type: v.optional(vTypeEnum49),
    station: vEventMetrics,
    network: vEventMetrics,
    similarStations: v.nullable(v.array(vStationEventRankingItem))
});

export const vTypeEnum50 = v.picklist(['STATION_DIRECTIONS']);

export const vStatisticsMetricResultStationDirectionsResult = v.object({
    type: v.optional(vTypeEnum50),
    items: v.array(vStationDirectionItem)
});

export const vTypeEnum51 = v.picklist(['STATION_EVENT_DETAILS']);

export const vStatisticsMetricResultStationEventDetailsResult = v.object({
    type: v.optional(vTypeEnum51),
    items: v.array(vStationEventDetailItem),
    page: vMetricPage
});

export const vTypeEnum52 = v.picklist(['STATION_LINE_RANKING']);

export const vStatisticsMetricResultStationLineRankingResult = v.object({
    type: v.optional(vTypeEnum52),
    items: v.array(vStationLineRankingItem),
    page: vMetricPage
});

export const vTypeEnum53 = v.picklist(['STATION_TIME_SERIES']);

export const vStatisticsMetricResultStationTimeSeriesResult = v.object({
    type: v.optional(vTypeEnum53),
    items: v.array(vEventTimeSeriesPoint)
});

export const vStatisticsMetricResult = v.union([
    v.intersect([v.object({
            type: v.optional(v.literal('EVENT_KPIS'))
        }), vStatisticsMetricResultEventKpisResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_KPIS'))
        }), vStatisticsMetricResultJourneyKpisResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('NETWORK_EVENT_TIME_SERIES'))
        }), vStatisticsMetricResultNetworkEventTimeSeriesResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('NETWORK_JOURNEY_TIME_SERIES'))
        }), vStatisticsMetricResultNetworkJourneyTimeSeriesResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('EVENT_WEEKDAY_HOUR_HEATMAP'))
        }), vStatisticsMetricResultEventWeekdayHourHeatmapResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_WEEKDAY_HOUR_HEATMAP'))
        }), vStatisticsMetricResultJourneyWeekdayHourHeatmapResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('TRANSPORT_TYPE_COMPARISON'))
        }), vStatisticsMetricResultTransportTypeComparisonResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('NETWORK_STATION_RANKING'))
        }), vStatisticsMetricResultNetworkStationRankingResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('NETWORK_LINE_RANKING'))
        }), vStatisticsMetricResultNetworkLineRankingResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('NETWORK_MAP_HOTSPOTS'))
        }), vStatisticsMetricResultNetworkMapHotspotsResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('STATION_BENCHMARK'))
        }), vStatisticsMetricResultStationBenchmarkResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('STATION_TIME_SERIES'))
        }), vStatisticsMetricResultStationTimeSeriesResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('ARRIVAL_DEPARTURE_COMPARISON'))
        }), vStatisticsMetricResultArrivalDepartureComparisonResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('STATION_LINE_RANKING'))
        }), vStatisticsMetricResultStationLineRankingResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('STATION_DIRECTIONS'))
        }), vStatisticsMetricResultStationDirectionsResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('TRANSPORT_TYPE_MIX'))
        }), vStatisticsMetricResultTransportTypeMixResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_HOUR_MATRIX'))
        }), vStatisticsMetricResultLineHourMatrixResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('STATION_EVENT_DETAILS'))
        }), vStatisticsMetricResultStationEventDetailsResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_SUMMARY'))
        }), vStatisticsMetricResultLineSummaryResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_TIME_SERIES'))
        }), vStatisticsMetricResultLineTimeSeriesResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_ROUTE_VARIANTS'))
        }), vStatisticsMetricResultLineRouteVariantsResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_STATION_PERFORMANCE'))
        }), vStatisticsMetricResultLineStationPerformanceResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_JOURNEY_NUMBER_RANKING'))
        }), vStatisticsMetricResultLineJourneyNumberRankingResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('LINE_PROBLEM_STATIONS'))
        }), vStatisticsMetricResultLineProblemStationsResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_PATTERN'))
        }), vStatisticsMetricResultJourneyPatternResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_DAILY_OUTCOMES'))
        }), vStatisticsMetricResultJourneyDailyOutcomesResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_STOP_PROFILE'))
        }), vStatisticsMetricResultJourneyStopProfileResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_DELAY_BUILD_UP'))
        }), vStatisticsMetricResultJourneyDelayBuildUpResult]),
    v.intersect([v.object({
            type: v.optional(v.literal('JOURNEY_CALENDAR'))
        }), vStatisticsMetricResultJourneyCalendarResult])
]);

export const vStatisticsMetricResponse = v.object({
    meta: vStatisticsResponseMeta,
    result: vStatisticsMetricResult
});
