// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

export const vBaseMetricDataPointBase = v.object({
	value: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])
});

export const vInformationType = v.picklist([
	"JOURNEY_ATTRIBUTE",
	"DISRUPTION",
	"MESSAGE",
	"RIS_QUALITY_DEVIATION",
	"RIS_CAUSE_REASON"
]);

export const vJourneyAdministration = v.object({
	administrationId: v.string(),
	operatorCode: v.string(),
	operatorName: v.string()
});

export const vJourneyRichStopPlace = v.object({
	cancelled: v.boolean(),
	name: v.string(),
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	])
});

export const vJourneyStopPlace = v.object({
	name: v.string(),
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	])
});

export const vJourneyType = v.picklist(["REGULAR", "REPLACEMENT", "RELIEF", "EXTRA"]);

export const vMessageKey = v.picklist([
	"UNPLANNED_INFO",
	"GENERAL_WARNING",
	"ADDITIONAL_COACHES",
	"MISSING_COACHES",
	"CHANGED_COACH_SEQUENCE",
	"REPLACEMENT_SERVICE",
	"ADDITIONAL_STOP",
	"WIFI_DISTRIBUTION",
	"NO_FIRST_CLASS",
	"ACCESSIBILITY_WARNING",
	"RESERVATIONS_MISSING",
	"RESERVATIONS_REQUIRED",
	"NO_FOOD",
	"BICYCLE_WARNING",
	"BICYCLE_TRANSPORT",
	"BICYCLE_TRANSPORT_NOT_POSSIBLE",
	"BICYCLE_RESERVATION_REQUIRED",
	"TICKET_INFORMATION"
]);

export const vMessageReferenceType = v.picklist(["LINK", "IMAGE", "ATTACHMENT"]);

export const vJourneyMessageReference = v.object({
	referenceType: vMessageReferenceType,
	url: v.optional(v.union([v.null(), v.string()])),
	label: v.optional(v.union([v.null(), v.string()]))
});

export const vMetricSeriesType = v.picklist([
	"DATABASE_SIZE",
	"RIS_IDS_ACTIVE",
	"RIS_IDS_INACTIVE",
	"JOURNEY_TOTAL",
	"TRANSPORT_TYPES_TOTAL",
	"HOURLY_GLOBAL_ARRIVALS",
	"HOURLY_GLOBAL_ARRIVAL_CANCELLATIONS",
	"HOURLY_GLOBAL_ARRIVAL_DELAY_SUM",
	"HOURLY_GLOBAL_DEPARTURES",
	"HOURLY_GLOBAL_DEPARTURE_CANCELLATIONS",
	"HOURLY_GLOBAL_DEPARTURE_DELAY_SUM",
	"STATION_ARRIVALS",
	"STATION_ARRIVAL_CANCELLATIONS",
	"STATION_ARRIVAL_DELAY_AVG",
	"STATION_DEPARTURES",
	"STATION_DEPARTURE_CANCELLATIONS",
	"STATION_DEPARTURE_DELAY_AVG"
]);

export const vMetricUnit = v.picklist(["BYTES", "COUNT", "SECONDS"]);

export const vProblemDetails = v.object({
	type: v.optional(v.union([v.null(), v.string()])),
	title: v.optional(v.union([v.null(), v.string()])),
	status: v.optional(
		v.union([
			v.null(),
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
				v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
			),
			v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
		])
	),
	detail: v.optional(v.union([v.null(), v.string()])),
	instance: v.optional(v.union([v.null(), v.string()]))
});

export const vScheduleType = v.picklist(["ARRIVAL", "DEPARTURE"]);

/**
 * Represents a request to find stations near specific geographic coordinates.
 */
export const vStationByGeographicCoordinatesRequest = v.object({
	latitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]),
	longitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]),
	limit: v.optional(
		v.union([
			v.null(),
			v.optional(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
					v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
				),
				100
			),
			v.optional(v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/)), 100)
		]),
		100
	),
	maxDistance: v.optional(
		v.union([
			v.null(),
			v.optional(v.number(), 1000),
			v.optional(v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/)), 1000)
		]),
		1000
	)
});

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location types.
 */
export const vStationBySerchtermRequest = v.object({
	searchTerm: v.string(),
	maxResults: v.optional(
		v.union([
			v.null(),
			v.optional(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
					v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
				),
				10
			),
			v.optional(v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/)), 10)
		]),
		10
	),
	locationTypes: v.optional(v.union([v.null(), v.optional(v.array(v.string()), ["ALL"])]), ["ALL"])
});

export const vStationPosition = v.object({
	latitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))]),
	longitude: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/))])
});

export const vBaseStation = v.object({
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	name: v.string(),
	position: vStationPosition
});

export const vTimetableEntryAdministration = v.object({
	administrationId: v.string(),
	operatorCode: v.string(),
	operatorName: v.string()
});

export const vTimetableEntryInformation = v.object({
	type: vInformationType,
	key: vMessageKey,
	text: v.string(),
	textShort: v.optional(v.union([v.null(), v.string()]))
});

export const vTimetableEntryRichStopPlace = v.object({
	cancelled: v.boolean(),
	additional: v.optional(v.union([v.null(), v.boolean()])),
	name: v.string(),
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	])
});

export const vTimetableEntryStopPlace = v.object({
	name: v.string(),
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	])
});

export const vTimetableEntryCoupledTransport = v.object({
	journeyId: v.string(),
	separationAt: vTimetableEntryStopPlace
});

/**
 * Represents a request to search for stations using a search term, with optional filters for result count and location types.
 */
export const vTimetableRequest = v.object({
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	when: v.optional(v.union([v.null(), v.pipe(v.string(), v.isoTimestamp())])),
	duration: v.optional(
		v.union([
			v.null(),
			v.optional(
				v.pipe(
					v.number(),
					v.integer(),
					v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
					v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
				),
				60
			),
			v.optional(v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/)), 60)
		]),
		60
	)
});

export const vTimeType = v.picklist(["SCHEDULE", "PREVIEW", "REAL"]);

export const vJourneyScheduledEvent = v.object({
	stopPlace: vJourneyStopPlace,
	differingStopPlace: vJourneyStopPlace,
	cancelled: v.boolean(),
	additional: v.boolean(),
	noPassengerChange: v.boolean(),
	demand: v.boolean(),
	scheduleType: vScheduleType,
	plannedTime: v.pipe(v.string(), v.isoTimestamp()),
	actualTime: v.pipe(v.string(), v.isoTimestamp()),
	delay: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	plannedPlatform: v.optional(v.union([v.null(), v.string()])),
	actualPlatform: v.optional(v.union([v.null(), v.string()])),
	timeType: vTimeType,
	travelsWith: v.optional(v.union([v.null(), v.array(v.string())])),
	messageIds: v.optional(
		v.union([
			v.null(),
			v.array(
				v.union([
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
						v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
					),
					v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
				])
			)
		])
	)
});

export const vTimetableEntrySchedule = v.object({
	plannedTime: v.pipe(v.string(), v.isoTimestamp()),
	actualTime: v.pipe(v.string(), v.isoTimestamp()),
	delay: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
				v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
			),
			v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
		])
	),
	plannedPlatform: v.optional(v.union([v.null(), v.string()])),
	actualPlatform: v.optional(v.union([v.null(), v.string()])),
	timeType: vTimeType
});

export const vTransportType = v.picklist([
	"UNKNOWN",
	"HIGH_SPEED_TRAIN",
	"INTERCITY_TRAIN",
	"INTER_REGIONAL_TRAIN",
	"REGIONAL_TRAIN",
	"CITY_TRAIN",
	"SUBWAY",
	"TRAM",
	"BUS",
	"FERRY",
	"FLIGHT",
	"CAR",
	"TAXI",
	"SHUTTLE",
	"BIKE",
	"SCOOTER",
	"WALK"
]);

export const vJourneyTransport = v.object({
	type: vTransportType,
	replacementType: v.optional(v.union([v.null(), vTransportType])),
	category: v.optional(v.union([v.null(), v.string()])),
	categoryInternal: v.optional(v.union([v.null(), v.string()])),
	journeyDescription: v.string(),
	number: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	line: v.optional(v.union([v.null(), v.string()]))
});

export const vStation = v.object({
	transports: v.array(vTransportType),
	ril100: v.optional(v.union([v.null(), v.array(v.string())])),
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	name: v.string(),
	position: vStationPosition
});

export const vStationGatheringInfo = v.object({
	queryingEnabled: v.boolean(),
	lastQueried: v.optional(v.union([v.null(), v.pipe(v.string(), v.isoTimestamp())])),
	active: v.array(vTransportType),
	disabled: v.array(vTransportType)
});

export const vTimetableEntryTransport = v.object({
	type: vTransportType,
	replacementType: v.optional(v.union([v.null(), vTransportType])),
	category: v.optional(v.union([v.null(), v.string()])),
	categoryInternal: v.optional(v.union([v.null(), v.string()])),
	journeyType: vJourneyType,
	journeyDescription: v.string(),
	number: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	line: v.optional(v.union([v.null(), v.string()]))
});

export const vTimetableArrival = v.object({
	journeyId: v.pipe(v.string(), v.maxLength(82)),
	administration: vTimetableEntryAdministration,
	transport: vTimetableEntryTransport,
	origin: vTimetableEntryRichStopPlace,
	differingOrigin: v.optional(v.union([v.null(), vTimetableEntryRichStopPlace])),
	direction: v.array(vTimetableEntryStopPlace),
	viaStops: v.array(vTimetableEntryRichStopPlace),
	schedule: vTimetableEntrySchedule,
	informations: v.array(vTimetableEntryInformation),
	cancelled: v.boolean(),
	additional: v.optional(v.union([v.null(), v.boolean()])),
	demand: v.optional(v.union([v.null(), v.boolean()])),
	travelsWith: v.optional(v.union([v.null(), v.array(v.string())]))
});

export const vTimetableDeparture = v.object({
	journeyId: v.pipe(v.string(), v.maxLength(82)),
	administration: vTimetableEntryAdministration,
	transport: vTimetableEntryTransport,
	destination: vTimetableEntryRichStopPlace,
	differingDestination: v.optional(v.union([v.null(), vTimetableEntryRichStopPlace])),
	direction: v.array(vTimetableEntryStopPlace),
	viaStops: v.array(vTimetableEntryRichStopPlace),
	schedule: vTimetableEntrySchedule,
	informations: v.array(vTimetableEntryInformation),
	cancelled: v.boolean(),
	additional: v.optional(v.union([v.null(), v.boolean()])),
	demand: v.optional(v.union([v.null(), v.boolean()])),
	travelsWith: v.optional(v.union([v.null(), v.array(vTimetableEntryCoupledTransport)]))
});

export const v__typeEnum = v.picklist(["evaNumber"]);

export const vBaseMetricDataPointStationDataPoint = v.object({
	$type: v__typeEnum,
	evaNumber: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	value: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])
});

export const v__typeEnum2 = v.picklist(["timestamp"]);

export const vBaseMetricDataPointTimestampDataPoint = v.object({
	$type: v__typeEnum2,
	timestamp: v.pipe(v.string(), v.isoTimestamp()),
	value: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])
});

export const v__typeEnum3 = v.picklist(["timestampTransportType"]);

export const vBaseMetricDataPointTimestampTransportTypeDataPoint = v.object({
	$type: v__typeEnum3,
	timestamp: v.pipe(v.string(), v.isoTimestamp()),
	transportType: vTransportType,
	value: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])
});

export const v__typeEnum4 = v.picklist(["transportType"]);

export const vBaseMetricDataPointTransportTypeDataPoint = v.object({
	$type: v__typeEnum4,
	transportType: vTransportType,
	value: v.union([v.number(), v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/))])
});

export const vBaseMetricDataPoint = v.union([
	vBaseMetricDataPointTimestampDataPoint,
	vBaseMetricDataPointTransportTypeDataPoint,
	vBaseMetricDataPointTimestampTransportTypeDataPoint,
	vBaseMetricDataPointStationDataPoint,
	vBaseMetricDataPointBase
]);

/**
 * Represents a series of measured data points for a specific metric.
 */
export const vMetricSeries = v.object({
	seriesType: vMetricSeriesType,
	unit: vMetricUnit,
	dataPoints: v.array(vBaseMetricDataPoint)
});

export const vQueryTypeEnum = v.picklist(["DATABASE_SIZE_SNAPSHOT"]);

export const vBaseMetricRequestDatabaseSizeSnapshotMetricRequest = v.object({
	queryType: v.optional(vQueryTypeEnum),
	start: v.pipe(v.string(), v.isoTimestamp()),
	end: v.pipe(v.string(), v.isoTimestamp())
});

export const vQueryTypeEnum2 = v.picklist(["HOURLY_TRANSPORT_SNAPSHOT"]);

export const vBaseMetricRequestHourlyTransportSnapshotMetricRequest = v.object({
	queryType: v.optional(vQueryTypeEnum2),
	seriesType: vMetricSeriesType,
	start: v.pipe(v.string(), v.isoTimestamp()),
	end: v.pipe(v.string(), v.isoTimestamp()),
	transportTypes: v.optional(v.union([v.null(), v.array(vTransportType)])),
	stepping: v.optional(
		v.union([
			v.pipe(
				v.number(),
				v.integer(),
				v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
				v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
			),
			v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
		])
	)
});

export const vQueryTypeEnum3 = v.picklist(["JOURNEY_SNAPSHOT"]);

export const vBaseMetricRequestJourneySnapshotMetricRequest = v.object({
	queryType: v.optional(vQueryTypeEnum3),
	start: v.pipe(v.string(), v.isoTimestamp()),
	end: v.pipe(v.string(), v.isoTimestamp())
});

export const vQueryTypeEnum4 = v.picklist(["RIS_ID_SNAPSHOT"]);

export const vBaseMetricRequestRisIdSnapshotMetricRequest = v.object({
	queryType: v.optional(vQueryTypeEnum4),
	seriesType: vMetricSeriesType,
	start: v.pipe(v.string(), v.isoTimestamp()),
	end: v.pipe(v.string(), v.isoTimestamp())
});

export const vQueryTypeEnum5 = v.picklist(["STATION_SUMMARY"]);

export const vBaseMetricRequestStationSummaryMetricRequest = v.object({
	queryType: v.optional(vQueryTypeEnum5),
	seriesType: vMetricSeriesType,
	start: v.optional(v.union([v.null(), v.pipe(v.string(), v.isoTimestamp())])),
	end: v.pipe(v.string(), v.isoTimestamp()),
	transportTypes: v.optional(v.union([v.null(), v.array(vTransportType)])),
	evaNumbers: v.optional(
		v.union([
			v.null(),
			v.array(
				v.union([
					v.pipe(
						v.number(),
						v.integer(),
						v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
						v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
					),
					v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
				])
			)
		])
	)
});

export const vQueryTypeEnum6 = v.picklist(["TRANSPORT_TYPE_DISTRIBUTION"]);

export const vBaseMetricRequestTransportTypeDistributionMetricRequest = v.object({
	queryType: v.optional(vQueryTypeEnum6),
	end: v.pipe(v.string(), v.isoTimestamp()),
	transportTypes: v.optional(v.union([v.null(), v.array(vTransportType)]))
});

export const vBaseMetricRequest = v.union([
	v.intersect([
		v.object({
			queryType: v.optional(v.literal("DATABASE_SIZE_SNAPSHOT"))
		}),
		vBaseMetricRequestDatabaseSizeSnapshotMetricRequest
	]),
	v.intersect([
		v.object({
			queryType: v.optional(v.literal("RIS_ID_SNAPSHOT"))
		}),
		vBaseMetricRequestRisIdSnapshotMetricRequest
	]),
	v.intersect([
		v.object({
			queryType: v.optional(v.literal("JOURNEY_SNAPSHOT"))
		}),
		vBaseMetricRequestJourneySnapshotMetricRequest
	]),
	v.intersect([
		v.object({
			queryType: v.optional(v.literal("TRANSPORT_TYPE_DISTRIBUTION"))
		}),
		vBaseMetricRequestTransportTypeDistributionMetricRequest
	]),
	v.intersect([
		v.object({
			queryType: v.optional(v.literal("HOURLY_TRANSPORT_SNAPSHOT"))
		}),
		vBaseMetricRequestHourlyTransportSnapshotMetricRequest
	]),
	v.intersect([
		v.object({
			queryType: v.optional(v.literal("STATION_SUMMARY"))
		}),
		vBaseMetricRequestStationSummaryMetricRequest
	])
]);

export const vTypeEnum = v.picklist(["ATTRIBUTE"]);

export const vJourneyMessageAttributeMessage = v.object({
	type: v.optional(vTypeEnum),
	messageId: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	key: vMessageKey,
	text: v.string()
});

export const vTypeEnum2 = v.picklist(["DISRUPTION"]);

export const vJourneyMessageDisruptionMessage = v.object({
	type: v.optional(vTypeEnum2),
	cause: v.optional(v.union([v.null(), v.string()])),
	effect: v.optional(v.union([v.null(), v.string()])),
	disruptionId: v.optional(v.union([v.null(), v.string()])),
	textShort: v.optional(v.union([v.null(), v.string()])),
	references: v.optional(v.union([v.null(), v.array(vJourneyMessageReference)])),
	messageId: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	key: vMessageKey,
	text: v.string()
});

export const vTypeEnum3 = v.picklist(["NOTE"]);

export const vJourneyMessageNoteMessage = v.object({
	type: v.optional(vTypeEnum3),
	category: v.optional(v.union([v.null(), v.string()])),
	textShort: v.optional(v.union([v.null(), v.string()])),
	references: v.optional(v.union([v.null(), v.array(vJourneyMessageReference)])),
	messageId: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	key: vMessageKey,
	text: v.string()
});

export const vTypeEnum4 = v.picklist(["RIS_CAUSE"]);

export const vJourneyMessageRisCauseMessage = v.object({
	type: v.optional(vTypeEnum4),
	messageId: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	key: vMessageKey,
	text: v.string()
});

export const vTypeEnum5 = v.picklist(["RIS_QUALITY_DEVIATION"]);

export const vJourneyMessageRisQualityDeviationMessage = v.object({
	type: v.optional(vTypeEnum5),
	messageId: v.union([
		v.pipe(
			v.number(),
			v.integer(),
			v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2^31"),
			v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2^31-1")
		),
		v.pipe(v.string(), v.regex(/^-?(?:0|[1-9]\d*)$/))
	]),
	key: vMessageKey,
	text: v.string()
});

export const vJourneyMessage = v.union([
	v.intersect([
		v.object({
			type: v.optional(v.literal("ATTRIBUTE"))
		}),
		vJourneyMessageAttributeMessage
	]),
	v.intersect([
		v.object({
			type: v.optional(v.literal("DISRUPTION"))
		}),
		vJourneyMessageDisruptionMessage
	]),
	v.intersect([
		v.object({
			type: v.optional(v.literal("NOTE"))
		}),
		vJourneyMessageNoteMessage
	]),
	v.intersect([
		v.object({
			type: v.optional(v.literal("RIS_CAUSE"))
		}),
		vJourneyMessageRisCauseMessage
	]),
	v.intersect([
		v.object({
			type: v.optional(v.literal("RIS_QUALITY_DEVIATION"))
		}),
		vJourneyMessageRisQualityDeviationMessage
	])
]);

export const vJourney = v.object({
	journeyId: v.pipe(v.string(), v.maxLength(82)),
	administration: vJourneyAdministration,
	type: vJourneyType,
	transport: vJourneyTransport,
	continuationBy: v.optional(v.array(v.string())),
	continuationFor: v.optional(v.array(v.string())),
	cancelled: v.boolean(),
	destination: vJourneyRichStopPlace,
	differingDestination: v.optional(v.union([v.null(), vJourneyStopPlace])),
	origin: vJourneyRichStopPlace,
	differingOrigin: v.optional(v.union([v.null(), vJourneyStopPlace])),
	scheduledEvents: v.array(vJourneyScheduledEvent),
	messages: v.array(vJourneyMessage)
});
