// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Navigator.Data;
using Navigator.Data.Enums;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Navigator.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251211201131_addStationGeoIndex")]
    partial class addStationGeoIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "information_type", new[] { "DISRUPTION", "JOURNEY_ATTRIBUTE", "MESSAGE", "RIS_CAUSE_REASON", "RIS_QUALITY_DEVIATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "schedule_type", new[] { "ARRIVAL", "DEPARTURE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "transport_type", new[] { "BIKE", "BUS", "CAR", "CITY_TRAIN", "FERRY", "FLIGHT", "HIGH_SPEED_TRAIN", "INTERCITY_TRAIN", "INTER_REGIONAL_TRAIN", "REGIONAL_TRAIN", "SCOOTER", "SHUTTLE", "SUBWAY", "TAXI", "TRAM", "UNKNOWN", "WALK" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "cube");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "earthdistance");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Administration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("administration_id");

                    b.Property<string>("OperatorCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operator_name");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationId", "OperatorCode", "OperatorName")
                        .IsUnique();

                    b.ToTable("journey_administrations", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserted_at");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationId");

                    b.HasIndex("Cancelled");

                    b.HasIndex("Date");

                    b.ToTable("journeys", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyScheduledStopPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actual_platform");

                    b.Property<DateTimeOffset>("ActualTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_time");

                    b.Property<bool>("Additional")
                        .HasColumnType("boolean")
                        .HasColumnName("additional");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Delay")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("delay")
                        .HasComputedColumnSql("EXTRACT(EPOCH FROM (actual_time - planned_time))::integer", true);

                    b.Property<bool>("Demand")
                        .HasColumnType("boolean")
                        .HasColumnName("demand");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<bool>("NoPassengerChange")
                        .HasColumnType("boolean")
                        .HasColumnName("no_passenger_change");

                    b.Property<string>("PlannedPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("planned_platform");

                    b.Property<DateTimeOffset>("PlannedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_time");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("station_name");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("JourneyId");

                    b.HasIndex("StationEvaNumber");

                    b.HasIndex("StationEvaNumber", "Date");

                    b.HasIndex("StationEvaNumber", "JourneyId");

                    b.ToTable("journey_scheduled_stop_places", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyStopPlaceInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DisruptionCommunicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("disruption_communication_id");

                    b.Property<Guid?>("DisruptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("disruption_id");

                    b.Property<string>("InformationKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<InformationType>("InformationType")
                        .HasColumnType("core.information_type")
                        .HasColumnName("information_type");

                    b.Property<Guid>("ScheduledStopPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_stop_place_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("text");

                    b.Property<string>("TextShort")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("text_short");

                    b.HasKey("Id");

                    b.HasIndex("InformationKey");

                    b.HasIndex("InformationType");

                    b.HasIndex("ScheduledStopPlaceId");

                    b.ToTable("journey_stop_place_informations", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyTransport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("CategoryInternal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_internal");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<string>("Line")
                        .HasColumnType("text")
                        .HasColumnName("line");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<TransportType?>("ReplacementTransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("replacement_transport_type");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("JourneyDescription");

                    b.HasIndex("Number");

                    b.HasIndex("ReplacementTransportType");

                    b.HasIndex("TransportType");

                    b.ToTable("journey_transports", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.RisId.RisId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTimeOffset?>("LastInsertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_insertion_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<TransportType?>("ReplacementTransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("replacement_transport_type");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("ReplacementTransportType");

                    b.HasIndex("TransportType");

                    b.ToTable("ris_ids", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Property<int>("EvaNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvaNumber"));

                    b.Property<DateTime?>("LastQueried")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_queried");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("QueryingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("querying_enabled");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("EvaNumber");

                    b.ToTable("stations", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<string>("Ril100Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ril100");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber");

                    b.ToTable("station_ril100", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber", "TransportType")
                        .IsUnique();

                    b.ToTable("station_transports", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.DatabaseSize", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.ToTable("database_size", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Administration", "Administration")
                        .WithMany()
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administration");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyScheduledStopPlace", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Journey", "Journey")
                        .WithMany("ScheduledStopPlaces")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyStopPlaceInformation", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.JourneyScheduledStopPlace", "ScheduledStopPlace")
                        .WithMany("Informations")
                        .HasForeignKey("ScheduledStopPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledStopPlace");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyTransport", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Journey", "Journey")
                        .WithOne("Transport")
                        .HasForeignKey("Navigator.Data.Entities.Journey.JourneyTransport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Ril100")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Transports")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.Navigation("ScheduledStopPlaces");

                    b.Navigation("Transport")
                        .IsRequired();
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyScheduledStopPlace", b =>
                {
                    b.Navigation("Informations");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Navigation("Ril100");

                    b.Navigation("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
