// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Navigator.Data;
using Navigator.Data.Enums;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Navigator.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251210211726_addStationGeoIndex")]
    partial class addStationGeoIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "transport_type", new[] { "BIKE", "BUS", "CAR", "CITY_TRAIN", "FERRY", "FLIGHT", "HIGH_SPEED_TRAIN", "INTERCITY_TRAIN", "INTER_REGIONAL_TRAIN", "REGIONAL_TRAIN", "SCOOTER", "SHUTTLE", "SUBWAY", "TAXI", "TRAM", "UNKNOWN", "WALK" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "cube");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "earthdistance");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Navigator.Data.Entities.RisId.RisId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTime?>("LastInsertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_insertion_at");

                    b.Property<TransportType?>("ReplacementTransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("replacement_transport_type");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.ToTable("ris_ids", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Property<int>("EvaNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvaNumber"));

                    b.Property<DateTime?>("LastQueried")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_queried");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("QueryingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("querying_enabled");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("EvaNumber");

                    b.ToTable("stations", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<string>("Ril100Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ril100");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber");

                    b.ToTable("station_ril100", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber", "TransportType")
                        .IsUnique();

                    b.ToTable("station_transports", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.DatabaseSize", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.ToTable("database_size", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Ril100")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Transports")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Navigation("Ril100");

                    b.Navigation("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
