// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Navigator.Data;
using Navigator.Data.Enums;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Navigator.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "information_type", new[] { "DISRUPTION", "JOURNEY_ATTRIBUTE", "MESSAGE", "RIS_CAUSE_REASON", "RIS_QUALITY_DEVIATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "journey_type", new[] { "EXTRA", "REGULAR", "RELIEF", "REPLACEMENT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "message_reference_type", new[] { "ATTACHMENT", "IMAGE", "LINK" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "message_type", new[] { "ATTRIBUTE", "DISRUPTION", "NOTE", "RIS_CAUSE", "RIS_QUALITY_DEVIATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "schedule_type", new[] { "ARRIVAL", "DEPARTURE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "time_type", new[] { "PREVIEW", "REAL", "SCHEDULE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "transport_type", new[] { "BIKE", "BUS", "CAR", "CITY_TRAIN", "FERRY", "FLIGHT", "HIGH_SPEED_TRAIN", "INTERCITY_TRAIN", "INTER_REGIONAL_TRAIN", "REGIONAL_TRAIN", "SCOOTER", "SHUTTLE", "SUBWAY", "TAXI", "TRAM", "UNKNOWN", "WALK" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "cube");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "earthdistance");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Administration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("administration_id");

                    b.Property<string>("OperatorCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operator_name");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationId", "OperatorCode", "OperatorName")
                        .IsUnique();

                    b.ToTable("journey_administrations", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("id");

                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserted_at");

                    b.Property<JourneyType>("JourneyType")
                        .HasColumnType("core.journey_type")
                        .HasColumnName("journey_type");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationId");

                    b.HasIndex("Cancelled");

                    b.HasIndex("Date");

                    b.HasIndex("InsertedAt");

                    b.HasIndex("JourneyType");

                    b.ToTable("journeys", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyStopPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actual_platform");

                    b.Property<short>("ActualTimeOffsetMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("actual_time_offset_minutes");

                    b.Property<DateTime>("ActualTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_time_utc");

                    b.Property<bool>("Additional")
                        .HasColumnType("boolean")
                        .HasColumnName("additional");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Delay")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("delay")
                        .HasComputedColumnSql("EXTRACT(EPOCH FROM (actual_time_utc - planned_time_utc))::integer", true);

                    b.Property<bool>("Demand")
                        .HasColumnType("boolean")
                        .HasColumnName("demand");

                    b.Property<string>("JourneyId")
                        .IsRequired()
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("journey_id");

                    b.Property<bool>("NoPassengerChange")
                        .HasColumnType("boolean")
                        .HasColumnName("no_passenger_change");

                    b.Property<string>("PlannedPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("planned_platform");

                    b.Property<short>("PlannedTimeOffsetMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("planned_time_offset_minutes");

                    b.Property<DateTime>("PlannedTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_time_utc");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("station_name");

                    b.Property<TimeType>("TimeType")
                        .HasColumnType("core.time_type")
                        .HasColumnName("time_type");

                    b.HasKey("Id");

                    b.HasIndex("ActualTimeUtc");

                    b.HasIndex("Date");

                    b.HasIndex("JourneyId");

                    b.HasIndex("PlannedTimeUtc");

                    b.HasIndex("StationEvaNumber", "Date");

                    b.HasIndex("StationEvaNumber", "JourneyId");

                    b.ToTable("journey_stop_places", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyTransport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("journey_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("CategoryInternal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_internal");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<string>("Line")
                        .HasColumnType("text")
                        .HasColumnName("line");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<TransportType?>("ReplacementTransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("replacement_transport_type");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("JourneyDescription");

                    b.HasIndex("Number");

                    b.HasIndex("ReplacementTransportType");

                    b.HasIndex("TransportType");

                    b.ToTable("journey_transports", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Message.JourneyMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("DisruptionCause")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("disruption_cause");

                    b.Property<string>("DisruptionEffect")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("disruption_effect");

                    b.Property<string>("JourneyId")
                        .IsRequired()
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("journey_id");

                    b.Property<string>("NoteCategory")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("note_category");

                    b.Property<string>("Text")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("text");

                    b.Property<string>("TextShort")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("text_short");

                    b.Property<MessageType>("Type")
                        .HasColumnType("core.message_type")
                        .HasColumnName("message_type");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("Type");

                    b.ToTable("journey_messages", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Message.JourneyMessageReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<MessageReferenceType>("ReferenceType")
                        .HasColumnType("core.message_reference_type")
                        .HasColumnName("message_reference_type");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("journey_message_references", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Message.JourneyStopPlaceMessage", b =>
                {
                    b.Property<Guid>("StopPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_stop_place_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_message_id");

                    b.HasKey("StopPlaceId", "MessageId");

                    b.HasIndex("MessageId");

                    b.HasIndex("StopPlaceId");

                    b.ToTable("journey_stop_place_messages", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.RisId.RisId", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(73)
                        .HasColumnType("character varying(73)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTime?>("LastInserted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inserted");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<TransportType?>("ReplacementTransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("replacement_transport_type");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveredAt");

                    b.HasIndex("LastInserted");

                    b.HasIndex("ReplacementTransportType");

                    b.HasIndex("TransportType");

                    b.HasIndex("Active", "LastSeen");

                    b.ToTable("ris_ids", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<DateTime?>("LastQueried")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_queried");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("QueryingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("querying_enabled");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("EvaNumber");

                    b.HasIndex("QueryingEnabled", "LastQueried");

                    b.ToTable("stations", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<string>("Ril100Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ril100");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber");

                    b.ToTable("station_ril100", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber", "TransportType")
                        .IsUnique();

                    b.ToTable("station_transports", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.DatabaseSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("database_size", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Administration", "Administration")
                        .WithMany()
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administration");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyStopPlace", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Journey", "Journey")
                        .WithMany("StopPlaces")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyTransport", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Journey", "Journey")
                        .WithOne("Transport")
                        .HasForeignKey("Navigator.Data.Entities.Journey.JourneyTransport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Message.JourneyMessage", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Journey", "Journey")
                        .WithMany("Messages")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Message.JourneyMessageReference", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Message.JourneyMessage", "Message")
                        .WithMany("References")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Message.JourneyStopPlaceMessage", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Message.JourneyMessage", "Message")
                        .WithMany("JourneyStopPlaceMessages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Navigator.Data.Entities.Journey.JourneyStopPlace", "StopPlace")
                        .WithMany("Messages")
                        .HasForeignKey("StopPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("StopPlace");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Ril100")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Transports")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("StopPlaces");

                    b.Navigation("Transport")
                        .IsRequired();
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyStopPlace", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Message.JourneyMessage", b =>
                {
                    b.Navigation("JourneyStopPlaceMessages");

                    b.Navigation("References");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Navigation("Ril100");

                    b.Navigation("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
