// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Navigator.Data;
using Navigator.Data.Enums;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Navigator.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "journey_type", new[] { "EXTRA", "REGULAR", "RELIEF", "REPLACEMENT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "schedule_type", new[] { "ARRIVAL", "DEPARTURE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "time_type", new[] { "PREVIEW", "REAL", "SCHEDULE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "core", "transport_type", new[] { "BIKE", "BUS", "CAR", "CITY_TRAIN", "FERRY", "FLIGHT", "HIGH_SPEED_TRAIN", "INTERCITY_TRAIN", "INTER_REGIONAL_TRAIN", "REGIONAL_TRAIN", "SCOOTER", "SHUTTLE", "SUBWAY", "TAXI", "TRAM", "UNKNOWN", "WALK" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "statistics", "statistics_refresh_queue_source", new[] { "JOURNEY_IMPORT", "MANUAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "statistics", "statistics_refresh_queue_status", new[] { "FAILED", "PENDING", "RUNNING", "SUCCESS" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "cube");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "earthdistance");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "timescaledb");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Administration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("administration_id");

                    b.Property<string>("OperatorCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operator_name");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationId", "OperatorCode", "OperatorName")
                        .IsUnique();

                    b.ToTable("journey_administrations", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserted_at");

                    b.Property<JourneyType>("JourneyType")
                        .HasColumnType("core.journey_type")
                        .HasColumnName("journey_type");

                    b.HasKey("Id", "Date");

                    b.HasIndex("AdministrationId");

                    b.ToTable("journeys", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyStopPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ActualPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actual_platform");

                    b.Property<DateTime>("ActualTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_time");

                    b.Property<bool>("Additional")
                        .HasColumnType("boolean")
                        .HasColumnName("additional");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<int>("Delay")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("delay")
                        .HasComputedColumnSql("EXTRACT(EPOCH FROM (actual_time - planned_time))::integer", true);

                    b.Property<bool>("Demand")
                        .HasColumnType("boolean")
                        .HasColumnName("demand");

                    b.Property<string>("JourneyId")
                        .IsRequired()
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("journey_id");

                    b.Property<bool>("NoPassengerChange")
                        .HasColumnType("boolean")
                        .HasColumnName("no_passenger_change");

                    b.Property<string>("PlannedPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("planned_platform");

                    b.Property<DateTime>("PlannedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_time");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<TimeType>("TimeType")
                        .HasColumnType("core.time_type")
                        .HasColumnName("time_type");

                    b.HasKey("Id", "Date");

                    b.HasIndex("JourneyId", "Date");

                    b.ToTable("journey_stop_places", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyTransport", b =>
                {
                    b.Property<string>("JourneyId")
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("journey_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("CategoryInternal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_internal");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<string>("Line")
                        .HasColumnType("text")
                        .HasColumnName("line");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<TransportType?>("ReplacementTransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("replacement_transport_type");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("JourneyId", "Date");

                    b.ToTable("journey_transports", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.RisId", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(73)
                        .HasColumnType("character varying(73)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTime?>("LastInserted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inserted");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<TransportType?>("ReplacementTransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("replacement_transport_type");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("Active", "LastSeen");

                    b.HasIndex("Active", "DiscoveredAt", "LastInserted");

                    b.ToTable("ris_ids", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<DateTime?>("LastQueried")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_queried");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("QueryingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("querying_enabled");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("EvaNumber");

                    b.HasIndex("QueryingEnabled", "LastQueried");

                    b.ToTable("stations", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<string>("Ril100Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ril100");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber", "Ril100Code")
                        .IsUnique();

                    b.ToTable("station_ril100", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber", "TransportType")
                        .IsUnique();

                    b.ToTable("station_transports", "core");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.DatabaseSizeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("database_size_snapshots", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.EventQualityHourlyRollup", b =>
                {
                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.Property<string>("JourneyDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<int>("JourneyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("journey_number");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<long>("CancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("cancelled_count");

                    b.Property<long>("Delay10To15MinutesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_10_to_15_minutes_count");

                    b.Property<long>("Delay15To30MinutesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_15_to_30_minutes_count");

                    b.Property<long>("Delay30To60MinutesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_30_to_60_minutes_count");

                    b.Property<long>("Delay5To10MinutesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_5_to_10_minutes_count");

                    b.Property<long>("DelayLessThan5MinutesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_less_than_5_minutes_count");

                    b.Property<long>("DelayMoreThan60MinutesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_more_than_60_minutes_count");

                    b.Property<long>("DelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_sum_seconds");

                    b.Property<long>("DelayedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("delayed_count");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<long>("PunctualCount")
                        .HasColumnType("bigint")
                        .HasColumnName("punctual_count");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshed_at");

                    b.HasKey("BucketHour", "StationEvaNumber", "ScheduleType", "AdministrationId", "TransportType", "JourneyDescription", "JourneyNumber", "OriginEvaNumber", "DestinationEvaNumber", "IsReplacement");

                    b.ToTable("event_quality_hourly_rollups", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.JourneyQualityHourlyRollup", b =>
                {
                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.Property<string>("JourneyDescription")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<int>("JourneyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("journey_number");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<long>("CompletedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_count");

                    b.Property<long>("DestinationDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_delay_sum_seconds");

                    b.Property<long>("DestinationDelayedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_delayed_count");

                    b.Property<long>("DestinationNotReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_not_reached_count");

                    b.Property<long>("DestinationNotReachedWithoutFullCancelCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_not_reached_without_full_cancel_count");

                    b.Property<long>("DestinationPunctualCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_count");

                    b.Property<long>("DestinationReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_reached_count");

                    b.Property<long>("FullyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("fully_cancelled_count");

                    b.Property<long>("JourneyCount")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_count");

                    b.Property<long>("PartiallyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("partially_cancelled_count");

                    b.Property<long>("PartiallyCancelledDestinationReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("partially_cancelled_destination_reached_count");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshed_at");

                    b.HasKey("BucketHour", "AdministrationId", "TransportType", "JourneyDescription", "JourneyNumber", "OriginEvaNumber", "DestinationEvaNumber", "IsReplacement");

                    b.ToTable("journey_quality_hourly_rollups", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.JourneySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("journey_snapshots", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.RisIdReactivationHold", b =>
                {
                    b.Property<string>("RisId")
                        .HasMaxLength(73)
                        .HasColumnType("character varying(73)")
                        .HasColumnName("ris_id");

                    b.Property<int>("ActivationCount")
                        .HasColumnType("integer")
                        .HasColumnName("activation_count");

                    b.Property<DateTime?>("LastInsertedAtReactivation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inserted_at_reactivation");

                    b.Property<DateTime?>("LastSeenAtReactivation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_reactivation");

                    b.Property<DateTime>("ProtectUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("protect_until");

                    b.Property<DateTime>("ReactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reactivated_at");

                    b.HasKey("RisId");

                    b.HasIndex("ProtectUntil");

                    b.ToTable("ris_id_reactivation_holds", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.RisIdSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Active")
                        .HasColumnType("integer")
                        .HasColumnName("active");

                    b.Property<int>("Inactive")
                        .HasColumnType("integer")
                        .HasColumnName("inactive");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("risid_snapshots", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.StatisticsRefreshProgress", b =>
                {
                    b.Property<string>("Operation")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<int>("CaggRefreshCount")
                        .HasColumnType("integer")
                        .HasColumnName("cagg_refresh_count");

                    b.Property<string>("ErrorKind")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_kind");

                    b.Property<long>("EventRowsAffected")
                        .HasColumnType("bigint")
                        .HasColumnName("event_rows_affected");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("JourneyRowsAffected")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_rows_affected");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Operation", "WindowStart", "WindowEnd");

                    b.ToTable("statistics_refresh_progress", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Statistics.StatisticsRefreshQueueItem", b =>
                {
                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("ErrorKind")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_kind");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTime>("FirstMarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_marked_at");

                    b.Property<DateTime>("LastMarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_marked_at");

                    b.Property<int>("MarkCount")
                        .HasColumnType("integer")
                        .HasColumnName("mark_count");

                    b.Property<StatisticsRefreshQueueSource>("Source")
                        .HasColumnType("statistics.statistics_refresh_queue_source")
                        .HasColumnName("source");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<StatisticsRefreshQueueStatus>("Status")
                        .HasColumnType("statistics.statistics_refresh_queue_status")
                        .HasColumnName("status");

                    b.HasKey("WindowStart", "WindowEnd");

                    b.HasIndex("LastMarkedAt");

                    b.HasIndex("Status", "WindowStart", "WindowEnd");

                    b.ToTable("statistics_refresh_queue", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.JourneyAdministrationQualityHourly", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("DestinationDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_delay_sum_seconds");

                    b.Property<long>("DestinationLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_30_count");

                    b.Property<long>("DestinationLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_60_count");

                    b.Property<long>("DestinationNotReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_not_reached_count");

                    b.Property<long>("DestinationPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_positive_delay_sum_seconds");

                    b.Property<long>("DestinationPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_15_count");

                    b.Property<long>("DestinationPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_5_count");

                    b.Property<long>("FullyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("fully_cancelled_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<long>("JourneyCount")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_count");

                    b.Property<long>("PartiallyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("partially_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("journey_administration_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("journey_administration_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.JourneyNumberQualityHourly", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("DestinationDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_delay_sum_seconds");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<long>("DestinationLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_30_count");

                    b.Property<long>("DestinationLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_60_count");

                    b.Property<long>("DestinationNotReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_not_reached_count");

                    b.Property<long>("DestinationPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_positive_delay_sum_seconds");

                    b.Property<long>("DestinationPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_15_count");

                    b.Property<long>("DestinationPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_5_count");

                    b.Property<long>("FullyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("fully_cancelled_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<long>("JourneyCount")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_count");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<int>("JourneyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("journey_number");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<long>("PartiallyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("partially_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("journey_number_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("journey_number_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.JourneyQualityDetail", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<int?>("DestinationDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("destination_delay_seconds");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<bool>("DestinationNotReached")
                        .HasColumnType("boolean")
                        .HasColumnName("destination_not_reached");

                    b.Property<bool>("FullyCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("fully_cancelled");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<DateOnly>("JourneyDate")
                        .HasColumnType("date")
                        .HasColumnName("journey_date");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<DateTime>("JourneyEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("journey_end_time");

                    b.Property<string>("JourneyId")
                        .IsRequired()
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("journey_id");

                    b.Property<int>("JourneyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("journey_number");

                    b.Property<DateTime>("JourneyStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("journey_start_time");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<bool>("PartiallyCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("partially_cancelled");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("journey_quality_details", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("journey_quality_details", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.LineEventQualityHourly", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<long>("EventDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_delay_sum_seconds");

                    b.Property<long>("EventLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_30_count");

                    b.Property<long>("EventLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_60_count");

                    b.Property<long>("EventPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_positive_delay_sum_seconds");

                    b.Property<long>("EventPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_15_count");

                    b.Property<long>("EventPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_5_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<long>("StopCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stop_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("line_event_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("line_event_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.LineJourneyQualityHourly", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("DestinationDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_delay_sum_seconds");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<long>("DestinationLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_30_count");

                    b.Property<long>("DestinationLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_60_count");

                    b.Property<long>("DestinationNotReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_not_reached_count");

                    b.Property<long>("DestinationPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_positive_delay_sum_seconds");

                    b.Property<long>("DestinationPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_15_count");

                    b.Property<long>("DestinationPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_5_count");

                    b.Property<long>("FullyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("fully_cancelled_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<long>("JourneyCount")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_count");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<long>("PartiallyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("partially_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("line_journey_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("line_journey_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.NetworkEventDelayDistributionHourly", b =>
                {
                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("DelayGte0Lt5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_0_lt_5_count");

                    b.Property<long>("DelayGte10Lt15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_10_lt_15_count");

                    b.Property<long>("DelayGte120Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_120_count");

                    b.Property<long>("DelayGte15Lt30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_15_lt_30_count");

                    b.Property<long>("DelayGte30Lt60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_30_lt_60_count");

                    b.Property<long>("DelayGte5Lt10Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_5_lt_10_count");

                    b.Property<long>("DelayGte60Lt120Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_60_lt_120_count");

                    b.Property<long>("DelayGteMinus5Lt0Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_gte_minus_5_lt_0_count");

                    b.Property<long>("DelayLtMinus5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("delay_lt_minus_5_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("network_event_delay_distribution_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("network_event_delay_distribution_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.NetworkEventQualityHourly", b =>
                {
                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<long>("EventDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_delay_sum_seconds");

                    b.Property<long>("EventLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_30_count");

                    b.Property<long>("EventLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_60_count");

                    b.Property<long>("EventPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_positive_delay_sum_seconds");

                    b.Property<long>("EventPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_15_count");

                    b.Property<long>("EventPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_5_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<long>("StopCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stop_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("network_event_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("network_event_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.NetworkJourneyOutcomeHourly", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("CompletedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_count");

                    b.Property<long>("DestinationNotReachedWithoutFullCancelCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_not_reached_without_full_cancel_count");

                    b.Property<long>("FullyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("fully_cancelled_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<long>("JourneyCount")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_count");

                    b.Property<long>("PartiallyCancelledDestinationReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("partially_cancelled_destination_reached_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("network_journey_outcome_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("network_journey_outcome_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.NetworkJourneyQualityHourly", b =>
                {
                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("DestinationDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_delay_sum_seconds");

                    b.Property<long>("DestinationLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_30_count");

                    b.Property<long>("DestinationLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_late_60_count");

                    b.Property<long>("DestinationNotReachedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_not_reached_count");

                    b.Property<long>("DestinationPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_positive_delay_sum_seconds");

                    b.Property<long>("DestinationPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_15_count");

                    b.Property<long>("DestinationPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_punctual_5_count");

                    b.Property<long>("FullyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("fully_cancelled_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<long>("JourneyCount")
                        .HasColumnType("bigint")
                        .HasColumnName("journey_count");

                    b.Property<long>("PartiallyCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("partially_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("network_journey_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("network_journey_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.StationAdministrationQualityHourly", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<long>("EventDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_delay_sum_seconds");

                    b.Property<long>("EventLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_30_count");

                    b.Property<long>("EventLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_60_count");

                    b.Property<long>("EventPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_positive_delay_sum_seconds");

                    b.Property<long>("EventPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_15_count");

                    b.Property<long>("EventPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_5_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<long>("StopCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stop_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("station_administration_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("station_administration_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.StationEventQualityHourly", b =>
                {
                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<long>("EventDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_delay_sum_seconds");

                    b.Property<long>("EventLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_30_count");

                    b.Property<long>("EventLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_60_count");

                    b.Property<long>("EventPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_positive_delay_sum_seconds");

                    b.Property<long>("EventPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_15_count");

                    b.Property<long>("EventPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_5_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<long>("StopCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stop_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("station_event_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("station_event_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.StationJourneyEventDetail", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<int>("EventDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("event_delay_seconds");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<DateOnly>("JourneyDate")
                        .HasColumnType("date")
                        .HasColumnName("journey_date");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<DateTime>("JourneyEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("journey_end_time");

                    b.Property<string>("JourneyId")
                        .IsRequired()
                        .HasMaxLength(82)
                        .HasColumnType("character varying(82)")
                        .HasColumnName("journey_id");

                    b.Property<int>("JourneyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("journey_number");

                    b.Property<DateTime>("JourneyStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("journey_start_time");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<DateTime>("PlannedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_time");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<bool>("StopCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("stop_cancelled");

                    b.Property<Guid>("StopPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("stop_place_id");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("station_journey_event_details", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("station_journey_event_details", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Views.StationLineQualityHourly", b =>
                {
                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id");

                    b.Property<DateTime>("BucketHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket_hour");

                    b.Property<int>("DestinationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("destination_eva_number");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<long>("EventDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_delay_sum_seconds");

                    b.Property<long>("EventLate30Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_30_count");

                    b.Property<long>("EventLate60Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_late_60_count");

                    b.Property<long>("EventPositiveDelaySumSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("event_positive_delay_sum_seconds");

                    b.Property<long>("EventPunctual15Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_15_count");

                    b.Property<long>("EventPunctual5Count")
                        .HasColumnType("bigint")
                        .HasColumnName("event_punctual_5_count");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("is_replacement");

                    b.Property<string>("JourneyDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("journey_description");

                    b.Property<int>("OriginEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("origin_eva_number");

                    b.Property<ScheduleType>("ScheduleType")
                        .HasColumnType("core.schedule_type")
                        .HasColumnName("schedule_type");

                    b.Property<int>("StationEvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<long>("StopCancelledCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stop_cancelled_count");

                    b.Property<TransportType>("TransportType")
                        .HasColumnType("core.transport_type")
                        .HasColumnName("transport_type");

                    b.ToTable("station_line_quality_hourly", "statistics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("station_line_quality_hourly", "statistics");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Administration", "Administration")
                        .WithMany()
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administration");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyStopPlace", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Journey", "Journey")
                        .WithMany("StopPlaces")
                        .HasForeignKey("JourneyId", "Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.JourneyTransport", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Journey.Journey", "Journey")
                        .WithOne("Transport")
                        .HasForeignKey("Navigator.Data.Entities.Journey.JourneyTransport", "JourneyId", "Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationRil100", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Ril100")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.StationTransport", b =>
                {
                    b.HasOne("Navigator.Data.Entities.Station.Station", "Station")
                        .WithMany("Transports")
                        .HasForeignKey("EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Navigator.Data.Entities.Journey.Journey", b =>
                {
                    b.Navigation("StopPlaces");

                    b.Navigation("Transport")
                        .IsRequired();
                });

            modelBuilder.Entity("Navigator.Data.Entities.Station.Station", b =>
                {
                    b.Navigation("Ril100");

                    b.Navigation("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
