using System.Text.Json.Serialization;

namespace Navigator.Data.Models.Statistics.Api;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(EventSummaryResult), "EVENT_SUMMARY")]
[JsonDerivedType(typeof(JourneySummaryResult), "JOURNEY_SUMMARY")]
[JsonDerivedType(typeof(NetworkEventTimeSeriesResult), "NETWORK_EVENT_TIME_SERIES")]
[JsonDerivedType(typeof(NetworkJourneyTimeSeriesResult), "NETWORK_JOURNEY_TIME_SERIES")]
[JsonDerivedType(typeof(NetworkJourneyOutcomeTimeSeriesResult), "NETWORK_JOURNEY_OUTCOME_TIME_SERIES")]
[JsonDerivedType(typeof(EventWeekdayHourHeatmapResult), "EVENT_WEEKDAY_HOUR_HEATMAP")]
[JsonDerivedType(typeof(JourneyWeekdayHourHeatmapResult), "JOURNEY_WEEKDAY_HOUR_HEATMAP")]
[JsonDerivedType(typeof(TransportTypeComparisonResult), "TRANSPORT_TYPE_COMPARISON")]
[JsonDerivedType(typeof(NetworkStationRankingResult), "NETWORK_STATION_RANKING")]
[JsonDerivedType(typeof(NetworkLineRankingResult), "NETWORK_LINE_RANKING")]
[JsonDerivedType(typeof(NetworkMapHotspotsResult), "NETWORK_MAP_HOTSPOTS")]
[JsonDerivedType(typeof(EventDelayDistributionResult), "EVENT_DELAY_DISTRIBUTION")]
[JsonDerivedType(typeof(StationBenchmarkResult), "STATION_BENCHMARK")]
[JsonDerivedType(typeof(StationTimeSeriesResult), "STATION_TIME_SERIES")]
[JsonDerivedType(typeof(ArrivalDepartureComparisonResult), "ARRIVAL_DEPARTURE_COMPARISON")]
[JsonDerivedType(typeof(StationLineRankingResult), "STATION_LINE_RANKING")]
[JsonDerivedType(typeof(StationDirectionsResult), "STATION_DIRECTIONS")]
[JsonDerivedType(typeof(TransportTypeMixResult), "TRANSPORT_TYPE_MIX")]
[JsonDerivedType(typeof(LineHourMatrixResult), "LINE_HOUR_MATRIX")]
[JsonDerivedType(typeof(StationEventDetailsResult), "STATION_EVENT_DETAILS")]
[JsonDerivedType(typeof(LineProfileResult), "LINE_PROFILE")]
[JsonDerivedType(typeof(LineTimeSeriesResult), "LINE_TIME_SERIES")]
[JsonDerivedType(typeof(LineRouteVariantsResult), "LINE_ROUTE_VARIANTS")]
[JsonDerivedType(typeof(LineStationPerformanceResult), "LINE_STATION_PERFORMANCE")]
[JsonDerivedType(typeof(LineJourneyNumberRankingResult), "LINE_JOURNEY_NUMBER_RANKING")]
[JsonDerivedType(typeof(LineProblemStationsResult), "LINE_PROBLEM_STATIONS")]
[JsonDerivedType(typeof(JourneyPatternResult), "JOURNEY_PATTERN")]
[JsonDerivedType(typeof(JourneyDailyOutcomesResult), "JOURNEY_DAILY_OUTCOMES")]
[JsonDerivedType(typeof(JourneyStopProfileResult), "JOURNEY_STOP_PROFILE")]
[JsonDerivedType(typeof(JourneyDelayBuildUpResult), "JOURNEY_DELAY_BUILD_UP")]
[JsonDerivedType(typeof(JourneyCalendarResult), "JOURNEY_CALENDAR")]
public abstract record StatisticsMetricResult;
