// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using daemon.Database;

#nullable disable

namespace daemon.Migrations
{
    [DbContext(typeof(NavigatorDbContext))]
    [Migration("20250527203001_Initial database migration")]
    partial class Initialdatabasemigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("daemon.Models.Database.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer")
                        .HasColumnName("station_eva_number");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber")
                        .IsUnique();

                    b.ToTable("station_coordinates", "core");
                });

            modelBuilder.Entity("daemon.Models.Database.Station", b =>
                {
                    b.Property<int>("EvaNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eva_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvaNumber"));

                    b.Property<DateTime?>("LastQueried")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_queried");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Products")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("products");

                    b.Property<bool?>("QueryingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("querying_enabled");

                    b.PrimitiveCollection<List<string>>("Ril100")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ril100");

                    b.HasKey("EvaNumber");

                    b.HasIndex("EvaNumber")
                        .IsUnique();

                    b.ToTable("stations", "core");
                });

            modelBuilder.Entity("daemon.Models.Database.Coordinates", b =>
                {
                    b.HasOne("daemon.Models.Database.Station", "Station")
                        .WithOne("Coordinates")
                        .HasForeignKey("daemon.Models.Database.Coordinates", "EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("daemon.Models.Database.Station", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
