// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using stations.Database;

#nullable disable

namespace stations.Migrations
{
    [DbContext(typeof(StationDbContext))]
    [Migration("20250526141039_Ensure EvaNumber is unique")]
    partial class EnsureEvaNumberisunique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("stations.Models.Database.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaNumber")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber")
                        .IsUnique();

                    b.ToTable("station_coordinates", "data");
                });

            modelBuilder.Entity("stations.Models.Database.Station", b =>
                {
                    b.Property<int>("EvaNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvaNumber"));

                    b.Property<DateTime?>("LastQueried")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.PrimitiveCollection<List<string>>("Products")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool?>("QueryingEnabled")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Ril100")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("EvaNumber");

                    b.HasIndex("EvaNumber")
                        .IsUnique();

                    b.ToTable("stations", "data");
                });

            modelBuilder.Entity("stations.Models.Database.Coordinates", b =>
                {
                    b.HasOne("stations.Models.Database.Station", "Station")
                        .WithOne("Coordinates")
                        .HasForeignKey("stations.Models.Database.Coordinates", "EvaNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("stations.Models.Database.Station", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
