name: 'Build and Push Docker Images'
description: 'Builds and pushes a Docker image to GHCR'

inputs:
  image-name:
    description: 'Name of the Docker image to build'
    required: true
  context:
    description: 'Context directory for the Docker build'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata and tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}
        tags: |
          # Latest commit SHA 
          type=sha,format=short
          # nightly
          type=raw,value=nightly
          # 'latest' on master branch
          type=branch,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=min