namespace Navigator.Api.Enums;

public enum MessageKey
{
    UNPLANNED_INFO,
    GENERAL_WARNING,
    ADDITIONAL_COACHES,
    MISSING_COACHES,
    CHANGED_COACH_SEQUENCE,
    REPLACEMENT_SERVICE,
    ADDITIONAL_STOP,
    WIFI_DISTRIBUTION,
    NO_FIRST_CLASS,
    ACCESSIBILITY_WARNING,
    RESERVATIONS_MISSING,
    RESERVATIONS_REQUIRED,
    NO_FOOD,
    BICYCLE_WARNING,
    BICYCLE_TRANSPORT,
    BICYCLE_TRANSPORT_NOT_POSSIBLE,
    BICYCLE_RESERVATION_REQUIRED,
    TICKET_INFORMATION
}
