<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="RIS\RIS__Boards-1.6.0.json" />
    <None Remove="RIS\RIS__Journeys-2.9.3.json" />
  </ItemGroup>

  <ItemGroup>
    <OpenApiReference Include="RIS\RIS__Boards-1.6.0.json" />
    <OpenApiReference Include="RIS\RIS__Journeys-2.9.3.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

</Project>
