services:
  navigator-frontend:
    container_name: navigator-frontend
    image: ghcr.io/schmolldechse/navigator-frontend:latest
    restart: always
    ports: [ "16200:3000" ]
    depends_on:
      navigator-backend
    environment:
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL}
      PRIVATE_BACKEND_URL: ${PRIVATE_BACKEND_URL}

  navigator-backend:
    container_name: navigator-backend
    image: ghcr.io/schmolldechse/navigator-backend:latest
    restart: always
    ports: [ "16100:3000" ]
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL}