name: Build Docker Images

on:
  workflow_run:
    workflows: ["Linting Checks"]
    branches: ["*"]
    types: [completed]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/build-docker-image.yml
        with:
          image-name: navigator-frontend
          context: frontend

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/build-docker-image.yml
        with:
          image-name: navigator-backend
          context: backend

  build-daemon:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/build-docker-image.yml
        with:
          image-name: navigator-daemon
          context: daemon