name: Build Projects

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  check-backend-formatting:
    name: Check Code Formatting for Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet-format
        run: dotnet format backend/backend.slnx --verify-no-changes

  check-frontend-formatting:
    name: Check Code Formatting for Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --dev

      - name: Run prettier lint
        run: bun run lint
        working-directory: frontend
