name: Deploy to Development Environment

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    branches:
      - '*'
      - '!master'
    types: [completed]
  workflow_dispatch:

jobs:
  deploy-dev:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to development
        run: |
          echo "Deploying to development environment..."

          response=$(curl -w "%{http_code}" -s -X POST ${{ secrets.DEPLOYMENT_URL }} \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            -H "Content-Type: application/json")

          http_code=${response: -3}

          if [[ $http_code -ge 200 && $http_code -lt 300 ]]; then
            echo "Deployment successful (HTTP $http_code)"
          else
            echo "Deployment failed (HTTP $http_code)"
            exit 1
          fi