name: Linting Checks

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    name: Lint Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Frontend format check
        working-directory: frontend
        run: npm ci && npm run lint

  lint-backend:
    runs-on: ubuntu-latest
    name: Lint Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'v2.x'

      - name: Deno format check
        working-directory: backend
        run: deno fmt --check