name: Linting Checks

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    name: Lint Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        working-directory: frontend
        run: bun install --dev

      - name: Prettier format check
        working-directory: frontend
        run: bun lint

  lint-backend:
    runs-on: ubuntu-latest
    name: Lint Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        working-directory: backend
        run: bun install --dev

      - name: Prettier format check
        working-directory: backend
        run: bun lint