name: Linting and Formatting

on:
  push:
    branches: [github-ci]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '!.github/workflows/**'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: github-ci

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Frontend checks
      - name: Frontend lint
        working-directory: frontend
        run: npm ci && npm run lint

      - name: Frontend format
        working-directory: frontend
        run: npm run format

      # Backend checks
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '1.40.x'

      - name: Deno format check
        working-directory: backend
        run: deno task fmt:check

      - name: Apply Deno formatting
        working-directory: backend
        run: deno task fmt

      - name: Commit formatting changes
        uses: EndBug/add-and-commit@v9
        with:
          branch: github-ci
          default_author: github_actions
          message: 'style: automated code formatting'
          add: '*.ts *.js *.svelte *.json *.html'
